PROCEDURE FIDE_ESTADOS_INSERTAR_SP(P_ID_ESTADO NUMBER, P_NOMBRE_ESTADO VARCHAR2) IS
BEGIN
INSERT INTO FIDE_ESTADOS_TB (ID_ESTADO, NOMBRE_ESTADO)
VALUES (P_ID_ESTADO, P_NOMBRE_ESTADO);
COMMIT;
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
DBMS_OUTPUT.PUT_LINE('YA EXISTE UN ESTADO CON EL ID ' || P_ID_ESTADO);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR ESTADO: ' || SQLERRM);
END FIDE_ESTADOS_INSERTAR_SP;

PROCEDURE FIDE_ROLES_INSERTAR_SP(P_ID_ROL NUMBER, P_ROL VARCHAR2, P_ID_ESTADO NUMBER) IS
BEGIN
INSERT INTO FIDE_ROLES_TB (ID_ROL, ROL, ID_ESTADO)
VALUES (P_ID_ROL, P_ROL, P_ID_ESTADO);
COMMIT;
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
DBMS_OUTPUT.PUT_LINE('YA EXISTE UN ROL CON EL ID ' || P_ID_ROL);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR ROL: ' || SQLERRM);
END FIDE_ROLES_INSERTAR_SP;

PROCEDURE FIDE_TIPOS_PAGO_INSERTAR_SP(P_ID_TIPO_PAGO NUMBER, P_TIPO VARCHAR2, P_ID_ESTADO NUMBER) IS
BEGIN
INSERT INTO FIDE_TIPOS_PAGO_TB (ID_TIPO_PAGO, TIPO, ID_ESTADO)
VALUES (P_ID_TIPO_PAGO, P_TIPO, P_ID_ESTADO);
COMMIT;
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
DBMS_OUTPUT.PUT_LINE('YA EXISTE UN TIPO DE PAGO CON EL ID ' || P_ID_TIPO_PAGO);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR TIPO DE PAGO: ' || SQLERRM);
END FIDE_TIPOS_PAGO_INSERTAR_SP;

PROCEDURE FIDE_FORMAS_PAGOS_INSERTAR_SP(P_ID_FORMA_PAGO NUMBER, P_FORMA VARCHAR2, P_ID_ESTADO NUMBER) IS
BEGIN
INSERT INTO FIDE_FORMAS_PAGOS_TB (ID_FORMA_PAGO, FORMA, ID_ESTADO)
VALUES (P_ID_FORMA_PAGO, P_FORMA, P_ID_ESTADO);
COMMIT;
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
DBMS_OUTPUT.PUT_LINE('YA EXISTE UNA FORMA DE PAGO CON EL ID ' || P_ID_FORMA_PAGO);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR FORMA DE PAGO: ' || SQLERRM);
END FIDE_FORMAS_PAGOS_INSERTAR_SP;

PROCEDURE FIDE_HORARIOS_TURNOS_INSERTAR_SP(P_ID_HORARIO NUMBER, P_HORARIO_TURNO VARCHAR2, P_ID_ESTADO NUMBER) IS
BEGIN
INSERT INTO FIDE_HORARIOS_TURNOS_TB (ID_HORARIO, HORARIO_TURNO, ID_ESTADO)
VALUES (P_ID_HORARIO, P_HORARIO_TURNO, P_ID_ESTADO);
COMMIT;
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
DBMS_OUTPUT.PUT_LINE('YA EXISTE UN HORARIO CON EL ID ' || P_ID_HORARIO);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR HORARIO DE TURNO: ' || SQLERRM);
END FIDE_HORARIOS_TURNOS_INSERTAR_SP;

PROCEDURE FIDE_FECHAS_TURNOS_INSERTAR_SP(P_ID_FECHAS NUMBER, P_FECHAS_TURNO DATE, P_ID_ESTADO NUMBER) IS
BEGIN
INSERT INTO FIDE_FECHAS_TURNOS_TB (ID_FECHAS, FECHAS_TURNO, ID_ESTADO)
VALUES (P_ID_FECHAS, P_FECHAS_TURNO, P_ID_ESTADO);
COMMIT;
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
DBMS_OUTPUT.PUT_LINE('YA EXISTE UNA FECHA DE TURNO CON EL ID ' || P_ID_FECHAS);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR FECHA DE TURNO: ' || SQLERRM);
END FIDE_FECHAS_TURNOS_INSERTAR_SP;

PROCEDURE FIDE_TIPOS_ESPACIOS_INSERTAR_SP(P_ID_TIPO_ESPACIO NUMBER, P_NOMBRE_ESPACIO VARCHAR2, P_DESCR_ESPACIO VARCHAR2, P_ID_ESTADO NUMBER) IS
BEGIN
INSERT INTO FIDE_TIPOS_ESPACIOS_TB (ID_TIPO_ESPACIO, NOMBRE_ESPACIO, DESCR_ESPACIO, ID_ESTADO)
VALUES (P_ID_TIPO_ESPACIO, P_NOMBRE_ESPACIO, P_DESCR_ESPACIO, P_ID_ESTADO);
COMMIT;
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
DBMS_OUTPUT.PUT_LINE('YA EXISTE UN TIPO DE ESPACIO CON EL ID ' || P_ID_TIPO_ESPACIO);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR TIPO DE ESPACIO: ' || SQLERRM);
END FIDE_TIPOS_ESPACIOS_INSERTAR_SP;

PROCEDURE FIDE_TIPOS_EVENTOS_INSERTAR_SP(P_ID_TIPO_EVENTO NUMBER, P_TIPO_EVENTO VARCHAR2, P_ID_ESTADO NUMBER) IS
BEGIN
INSERT INTO FIDE_TIPOS_EVENTOS_TB (ID_TIPO_EVENTO, TIPO_EVENTO, ID_ESTADO)
VALUES (P_ID_TIPO_EVENTO, P_TIPO_EVENTO, P_ID_ESTADO);
COMMIT;
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
DBMS_OUTPUT.PUT_LINE('YA EXISTE UN TIPO DE EVENTO CON EL ID ' || P_ID_TIPO_EVENTO);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR TIPO DE EVENTO: ' || SQLERRM);
END FIDE_TIPOS_EVENTOS_INSERTAR_SP;

PROCEDURE FIDE_TIPOS_SERVICIOS_INSERTAR_SP(P_ID_TIPO_SERVICIO NUMBER, P_TIPO_SERVICIO VARCHAR2, P_ID_ESTADO NUMBER) IS
BEGIN
INSERT INTO FIDE_TIPOS_SERVICIOS_TB (ID_TIPO_SERVICIO, TIPO_SERVICIO, ID_ESTADO)
VALUES (P_ID_TIPO_SERVICIO, P_TIPO_SERVICIO, P_ID_ESTADO);
COMMIT;
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
DBMS_OUTPUT.PUT_LINE('YA EXISTE UN TIPO DE SERVICIO CON EL ID ' || P_ID_TIPO_SERVICIO);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR TIPO DE SERVICIO: ' || SQLERRM);
END FIDE_TIPOS_SERVICIOS_INSERTAR_SP;

PROCEDURE FIDE_PERSONAS_INSERTAR_SP(P_ID_PERSONA NUMBER, P_NOMBRE VARCHAR2, P_APELLIDO_PATERNO VARCHAR2, P_APELLIDO_MATERNO VARCHAR2, P_FECHA_REGISTRO DATE, P_ID_ROL NUMBER, P_ID_ESTADO NUMBER) IS
BEGIN
INSERT INTO FIDE_PERSONAS_TB (ID_PERSONA, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_REGISTRO, ID_ROL, ID_ESTADO)
VALUES (P_ID_PERSONA, P_NOMBRE, P_APELLIDO_PATERNO, P_APELLIDO_MATERNO, P_FECHA_REGISTRO, P_ID_ROL, P_ID_ESTADO);
COMMIT;
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
DBMS_OUTPUT.PUT_LINE('YA EXISTE UNA PERSONA CON LA CEDULA ' || P_ID_PERSONA);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR PERSONA: ' || SQLERRM);
END FIDE_PERSONAS_INSERTAR_SP;

PROCEDURE FIDE_TELEFONOS_INSERTAR_SP(P_ID_TELEFONO NUMBER, P_ID_PERSONA NUMBER, P_TELEFONO VARCHAR2, P_ID_ESTADO NUMBER) IS
BEGIN
INSERT INTO FIDE_TELEFONOS_TB (ID_TELEFONO, ID_PERSONA, TELEFONO, ID_ESTADO)
VALUES (P_ID_TELEFONO, P_ID_PERSONA, P_TELEFONO, P_ID_ESTADO);
COMMIT;
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
DBMS_OUTPUT.PUT_LINE('YA EXISTE UN TELEFONO CON EL ID ' || P_ID_TELEFONO);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR TELEFONO: ' || SQLERRM);
END FIDE_TELEFONOS_INSERTAR_SP;

PROCEDURE FIDE_CORREOS_INSERTAR_SP(P_ID_CORREO NUMBER, P_ID_PERSONA NUMBER, P_CORREO VARCHAR2, P_ID_ESTADO NUMBER) IS
BEGIN
INSERT INTO FIDE_CORREOS_TB (ID_CORREO, ID_PERSONA, CORREO, ID_ESTADO)
VALUES (P_ID_CORREO, P_ID_PERSONA, P_CORREO, P_ID_ESTADO);
COMMIT;
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
DBMS_OUTPUT.PUT_LINE('YA EXISTE UN CORREO CON EL ID ' || P_ID_CORREO);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR CORREO: ' || SQLERRM);
END FIDE_CORREOS_INSERTAR_SP;

PROCEDURE FIDE_RESIDENCIAS_INSERTAR_SP(P_ID_RESIDENCIA NUMBER, P_MONTO_ALQUILER NUMBER, P_MONTO_MANTENIMIENTO NUMBER, P_ID_TIPO_PAGO NUMBER, P_ID_ESTADO NUMBER) IS
BEGIN
INSERT INTO FIDE_RESIDENCIAS_TB (ID_RESIDENCIA, MONTO_ALQUILER, MONTO_MANTENIMIENTO, ID_TIPO_PAGO, ID_ESTADO)
VALUES (P_ID_RESIDENCIA, P_MONTO_ALQUILER, P_MONTO_MANTENIMIENTO, P_ID_TIPO_PAGO, P_ID_ESTADO);
COMMIT;
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
DBMS_OUTPUT.PUT_LINE('YA EXISTE UNA RESIDENCIA CON EL ID ' || P_ID_RESIDENCIA);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR RESIDENCIA: ' || SQLERRM);
END FIDE_RESIDENCIAS_INSERTAR_SP;

PROCEDURE FIDE_RESIDENTES_INSERTAR_SP(P_ID_PERSONA NUMBER, P_ID_RESIDENCIA NUMBER, P_ID_ESTADO NUMBER) IS
BEGIN
INSERT INTO FIDE_RESIDENTES_TB (ID_PERSONA, ID_RESIDENCIA, ID_ESTADO)
VALUES (P_ID_PERSONA, P_ID_RESIDENCIA, P_ID_ESTADO);
COMMIT;
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
DBMS_OUTPUT.PUT_LINE('LA PERSONA ' || P_ID_PERSONA || ' YA ESTA REGISTRADA EN LA RESIDENCIA ' || P_ID_RESIDENCIA);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR RESIDENTE: ' || SQLERRM);
END FIDE_RESIDENTES_INSERTAR_SP;

PROCEDURE FIDE_EVENTOS_INSERTAR_SP(P_ID_EVENTO NUMBER, P_DESCR_EVENTO VARCHAR2, P_FECHA_EVENTO DATE, P_ID_TIPO_EVENTO NUMBER, P_ID_TIPO_ESPACIO NUMBER, P_ID_ESTADO NUMBER) IS
BEGIN
INSERT INTO FIDE_EVENTOS_TB (ID_EVENTO, DESCR_EVENTO, FECHA_EVENTO, ID_TIPO_EVENTO, ID_TIPO_ESPACIO, ID_ESTADO)
VALUES (P_ID_EVENTO, P_DESCR_EVENTO, P_FECHA_EVENTO, P_ID_TIPO_EVENTO, P_ID_TIPO_ESPACIO, P_ID_ESTADO);
COMMIT;
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
DBMS_OUTPUT.PUT_LINE('YA EXISTE UN EVENTO CON EL ID ' || P_ID_EVENTO);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR EVENTO: ' || SQLERRM);
END FIDE_EVENTOS_INSERTAR_SP;

PROCEDURE FIDE_VEHICULOS_INSERTAR_SP(P_PLACA VARCHAR2, P_DESCRIPCION VARCHAR2, P_ID_TIPO_ESPACIO NUMBER, P_ID_PERSONA NUMBER, P_ID_ESTADO NUMBER) IS
BEGIN
INSERT INTO FIDE_VEHICULOS_TB (PLACA, DESCRIPCION, ID_TIPO_ESPACIO, ID_PERSONA, ID_ESTADO)
VALUES (P_PLACA, P_DESCRIPCION, P_ID_TIPO_ESPACIO, P_ID_PERSONA, P_ID_ESTADO);
COMMIT;
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
DBMS_OUTPUT.PUT_LINE('YA EXISTE UN VEHICULO CON LA PLACA ' || P_PLACA);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR VEHICULO: ' || SQLERRM);
END FIDE_VEHICULOS_INSERTAR_SP;

PROCEDURE FIDE_SERVICIOS_INSERTAR_SP(P_ID_SERVICIO NUMBER, P_DESCR_SERVICIO VARCHAR2, P_FECHA_SALIDA DATE, P_ID_TIPO_SERVICIO NUMBER, P_ID_TIPO_EVENTO NUMBER, P_ID_ESTADO NUMBER) IS
BEGIN
INSERT INTO FIDE_SERVICIOS_TB (ID_SERVICIO, DESCR_SERVICIO, FECHA_SALIDA, ID_TIPO_SERVICIO, ID_TIPO_EVENTO, ID_ESTADO)
VALUES (P_ID_SERVICIO, P_DESCR_SERVICIO, P_FECHA_SALIDA, P_ID_TIPO_SERVICIO, P_ID_TIPO_EVENTO, P_ID_ESTADO);
COMMIT;
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
DBMS_OUTPUT.PUT_LINE('YA EXISTE UN SERVICIO CON EL ID ' || P_ID_SERVICIO);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR SERVICIO: ' || SQLERRM);
END FIDE_SERVICIOS_INSERTAR_SP;

PROCEDURE FIDE_FACTURAS_INSERTAR_SP(P_ID_FACTURA NUMBER, P_FECHA_FACTURA DATE, P_DESCR_FACTURA VARCHAR2, P_ID_TIPO_PAGO NUMBER, P_ID_FORMA_PAGO NUMBER, P_ID_PERSONA NUMBER, P_ID_ESTADO NUMBER) IS
BEGIN
INSERT INTO FIDE_FACTURAS_TB (ID_FACTURA, FECHA_FACTURA, DESCR_FACTURA, ID_TIPO_PAGO, ID_FORMA_PAGO, ID_PERSONA, ID_ESTADO)
VALUES (P_ID_FACTURA, P_FECHA_FACTURA, P_DESCR_FACTURA, P_ID_TIPO_PAGO, P_ID_FORMA_PAGO, P_ID_PERSONA, P_ID_ESTADO);
COMMIT;
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
DBMS_OUTPUT.PUT_LINE('YA EXISTE UNA FACTURA CON EL ID ' || P_ID_FACTURA);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR FACTURA: ' || SQLERRM);
END FIDE_FACTURAS_INSERTAR_SP;

PROCEDURE FIDE_CONSULTAS_INSERTAR_SP(P_ID_CONSULTA NUMBER, P_CONSULTA VARCHAR2, P_FECHA_CONSULTA DATE, P_ID_PERSONA NUMBER, P_ID_ESTADO NUMBER) IS
BEGIN
INSERT INTO FIDE_CONSULTAS_TB (ID_CONSULTA, CONSULTA, FECHA_CONSULTA, ID_PERSONA, ID_ESTADO)
VALUES (P_ID_CONSULTA, P_CONSULTA, P_FECHA_CONSULTA, P_ID_PERSONA, P_ID_ESTADO);
COMMIT;
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
DBMS_OUTPUT.PUT_LINE('YA EXISTE UNA CONSULTA CON EL ID ' || P_ID_CONSULTA);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR CONSULTA: ' || SQLERRM);
END FIDE_CONSULTAS_INSERTAR_SP;

PROCEDURE FIDE_REPORTES_INSERTAR_SP(P_ID_REPORTE NUMBER, P_REPORTE VARCHAR2, P_FECHA_REPORTE DATE, P_ID_PERSONA NUMBER, P_ID_ESTADO NUMBER) IS
BEGIN
INSERT INTO FIDE_REPORTES_TB (ID_REPORTE, REPORTE, FECHA_REPORTE, ID_PERSONA, ID_ESTADO)
VALUES (P_ID_REPORTE, P_REPORTE, P_FECHA_REPORTE, P_ID_PERSONA, P_ID_ESTADO);
COMMIT;
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
DBMS_OUTPUT.PUT_LINE('YA EXISTE UN REPORTE CON EL ID ' || P_ID_REPORTE);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR REPORTE: ' || SQLERRM);
END FIDE_REPORTES_INSERTAR_SP;

PROCEDURE FIDE_SALARIOS_INSERTAR_SP(P_ID_PERSONA NUMBER, P_MONTO NUMBER, P_TIPO_PAGO NUMBER, P_ID_FORMA_PAGO NUMBER, P_ID_ESTADO NUMBER) IS
BEGIN
INSERT INTO FIDE_SALARIOS_TB (ID_PERSONA, MONTO, TIPO_PAGO, ID_FORMA_PAGO, ID_ESTADO)
VALUES (P_ID_PERSONA, P_MONTO, P_TIPO_PAGO, P_ID_FORMA_PAGO, P_ID_ESTADO);
COMMIT;
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
DBMS_OUTPUT.PUT_LINE('YA EXISTE UN SALARIO REGISTRADO PARA LA PERSONA ' || P_ID_PERSONA);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR SALARIO: ' || SQLERRM);
END FIDE_SALARIOS_INSERTAR_SP;

PROCEDURE FIDE_PAQUETES_INSERTAR_SP(P_ID_PAQUETE NUMBER, P_ID_PERSONA NUMBER, P_ID_RESIDENCIA NUMBER, P_FECHA_INGRESO DATE, P_FECHA_SALIDA DATE, P_ID_ESTADO NUMBER) IS
BEGIN
INSERT INTO FIDE_PAQUETES_TB (ID_PAQUETE, ID_PERSONA, ID_RESIDENCIA, FECHA_INGRESO, FECHA_SALIDA, ID_ESTADO)
VALUES (P_ID_PAQUETE, P_ID_PERSONA, P_ID_RESIDENCIA, P_FECHA_INGRESO, P_FECHA_SALIDA, P_ID_ESTADO);
COMMIT;
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
DBMS_OUTPUT.PUT_LINE('YA EXISTE UN PAQUETE CON EL ID ' || P_ID_PAQUETE);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR PAQUETE: ' || SQLERRM);
END FIDE_PAQUETES_INSERTAR_SP;

PROCEDURE FIDE_TURNOS_INSERTAR_SP(P_ID_PERSONA NUMBER, P_ID_FECHAS NUMBER, P_ID_HORARIO NUMBER, P_ID_ESTADO NUMBER) IS
BEGIN
INSERT INTO FIDE_TURNOS_TB (ID_PERSONA, ID_FECHAS, ID_HORARIO, ID_ESTADO)
VALUES (P_ID_PERSONA, P_ID_FECHAS, P_ID_HORARIO, P_ID_ESTADO);
COMMIT;
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
DBMS_OUTPUT.PUT_LINE('YA EXISTE UN TURNO PARA LA PERSONA ' || P_ID_PERSONA || ' EN ESA FECHA Y HORARIO');
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR TURNO: ' || SQLERRM);
END FIDE_TURNOS_INSERTAR_SP;

PROCEDURE FIDE_VISITAS_INSERTAR_SP(P_ID_VISITA NUMBER, P_ID_PERSONA NUMBER, P_FECHA_INGRESO DATE, P_FECHA_SALIDA DATE, P_ID_RESIDENCIA NUMBER, P_ID_ROL NUMBER, P_ID_ESTADO NUMBER) IS
BEGIN
INSERT INTO FIDE_VISITAS_TB (ID_VISITA, ID_PERSONA, FECHA_INGRESO, FECHA_SALIDA, ID_RESIDENCIA, ID_ROL, ID_ESTADO)
VALUES (P_ID_VISITA, P_ID_PERSONA, P_FECHA_INGRESO, P_FECHA_SALIDA, P_ID_RESIDENCIA, P_ID_ROL, P_ID_ESTADO);
COMMIT;
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
DBMS_OUTPUT.PUT_LINE('YA EXISTE UNA VISITA CON EL ID ' || P_ID_VISITA);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR VISITA: ' || SQLERRM);
END FIDE_VISITAS_INSERTAR_SP;

PROCEDURE FIDE_PERSONAS_SERVICIOS_INSERTAR_SP(P_ID_SERVICIO NUMBER, P_ID_PERSONA NUMBER, P_ID_ESTADO NUMBER) IS
BEGIN
INSERT INTO FIDE_PERSONAS_SERVICIOS_TB (ID_SERVICIO, ID_PERSONA, ID_ESTADO)
VALUES (P_ID_SERVICIO, P_ID_PERSONA, P_ID_ESTADO);
COMMIT;
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
DBMS_OUTPUT.PUT_LINE('LA PERSONA ' || P_ID_PERSONA || ' YA ESTA ASIGNADA AL SERVICIO ' || P_ID_SERVICIO);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR ASIGNACION DE SERVICIO: ' || SQLERRM);
END FIDE_PERSONAS_SERVICIOS_INSERTAR_SP;

PROCEDURE FIDE_RESUMENES_TURNOS_INSERTAR_SP(P_ID_RESUMEN NUMBER, P_DESCRIPCION VARCHAR2, P_ID_FECHAS NUMBER, P_ID_HORARIO NUMBER, P_ID_CONSULTA NUMBER, P_ID_REPORTE NUMBER, P_ID_ESTADO NUMBER) IS
BEGIN
INSERT INTO FIDE_RESUMENES_TURNOS_TB (ID_RESUMEN, DESCRIPCION, ID_FECHAS, ID_HORARIO, ID_CONSULTA, ID_REPORTE, ID_ESTADO)
VALUES (P_ID_RESUMEN, P_DESCRIPCION, P_ID_FECHAS, P_ID_HORARIO, P_ID_CONSULTA, P_ID_REPORTE, P_ID_ESTADO);
COMMIT;
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
DBMS_OUTPUT.PUT_LINE('YA EXISTE UN RESUMEN DE TURNO CON EL ID ' || P_ID_RESUMEN);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR RESUMEN DE TURNO: ' || SQLERRM);
END FIDE_RESUMENES_TURNOS_INSERTAR_SP;