create or replace PACKAGE BODY FIDE_CONDOMINIO_PKG AS

    FUNCTION FIDE_TOTAL_FACTURAS_PERSONA_FN(P_ID_PERSONA NUMBER) RETURN NUMBER IS
    V_TOTAL NUMBER := 0;
    BEGIN
    FOR REG IN (
    SELECT COUNT(*) AS TOTAL
    FROM FIDE_FACTURAS_TB
    WHERE ID_PERSONA = P_ID_PERSONA
    ) LOOP
    V_TOTAL := REG.TOTAL;
    END LOOP;
    RETURN V_TOTAL;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRARON FACTURAS PARA LA PERSONA ' || P_ID_PERSONA);
    RETURN 0;
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL OBTENER FACTURAS DE PERSONA: ' || SQLERRM);
    RETURN 0;
    END FIDE_TOTAL_FACTURAS_PERSONA_FN;
    
    FUNCTION FIDE_MONTO_FACTURADO_PERSONA_FN(P_ID_PERSONA NUMBER) RETURN NUMBER IS
    V_TOTAL NUMBER := 0;
    BEGIN
    FOR REG IN (
    SELECT COUNT(F.ID_FACTURA) AS TOTAL
    FROM FIDE_FACTURAS_TB F
    WHERE F.ID_PERSONA = P_ID_PERSONA
    AND F.ID_ESTADO = 1
    ) LOOP
    V_TOTAL := REG.TOTAL;
    END LOOP;
    RETURN V_TOTAL;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRARON FACTURAS ACTIVAS PARA LA PERSONA ' || P_ID_PERSONA);
    RETURN 0;
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL OBTENER MONTO FACTURADO DE PERSONA: ' || SQLERRM);
    RETURN 0;
    END FIDE_MONTO_FACTURADO_PERSONA_FN;
    
    FUNCTION FIDE_TOTAL_VISITAS_RESIDENCIA_FN(P_ID_RESIDENCIA NUMBER) RETURN NUMBER IS
    V_TOTAL NUMBER := 0;
    BEGIN
    FOR REG IN (
    SELECT COUNT(*) AS TOTAL
    FROM FIDE_VISITAS_TB
    WHERE ID_RESIDENCIA = P_ID_RESIDENCIA
    ) LOOP
    V_TOTAL := REG.TOTAL;
    END LOOP;
    RETURN V_TOTAL;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRARON VISITAS PARA LA RESIDENCIA ' || P_ID_RESIDENCIA);
    RETURN 0;
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL OBTENER VISITAS DE RESIDENCIA: ' || SQLERRM);
    RETURN 0;
    END FIDE_TOTAL_VISITAS_RESIDENCIA_FN;
    
    FUNCTION FIDE_TOTAL_PAQUETES_RESIDENCIA_FN(P_ID_RESIDENCIA NUMBER) RETURN NUMBER IS
    V_TOTAL NUMBER := 0;
    BEGIN
    FOR REG IN (
    SELECT COUNT(*) AS TOTAL
    FROM FIDE_PAQUETES_TB
    WHERE ID_RESIDENCIA = P_ID_RESIDENCIA
    ) LOOP
    V_TOTAL := REG.TOTAL;
    END LOOP;
    RETURN V_TOTAL;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRARON PAQUETES PARA LA RESIDENCIA ' || P_ID_RESIDENCIA);
    RETURN 0;
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL OBTENER PAQUETES DE RESIDENCIA: ' || SQLERRM);
    RETURN 0;
    END FIDE_TOTAL_PAQUETES_RESIDENCIA_FN;
    
    FUNCTION FIDE_TOTAL_VEHICULOS_PERSONA_FN(P_ID_PERSONA NUMBER) RETURN NUMBER IS
    V_TOTAL NUMBER := 0;
    BEGIN
    FOR REG IN (
    SELECT COUNT(*) AS TOTAL
    FROM FIDE_VEHICULOS_TB
    WHERE ID_PERSONA = P_ID_PERSONA
    ) LOOP
    V_TOTAL := REG.TOTAL;
    END LOOP;
    RETURN V_TOTAL;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRARON VEHICULOS PARA LA PERSONA ' || P_ID_PERSONA);
    RETURN 0;
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL OBTENER VEHICULOS DE PERSONA: ' || SQLERRM);
    RETURN 0;
    END FIDE_TOTAL_VEHICULOS_PERSONA_FN;
    
    FUNCTION FIDE_TOTAL_SERVICIOS_PERSONA_FN(P_ID_PERSONA NUMBER) RETURN NUMBER IS
    V_TOTAL NUMBER := 0;
    BEGIN
    FOR REG IN (
    SELECT COUNT(*) AS TOTAL
    FROM FIDE_PERSONAS_SERVICIOS_TB
    WHERE ID_PERSONA = P_ID_PERSONA
    ) LOOP
    V_TOTAL := REG.TOTAL;
    END LOOP;
    RETURN V_TOTAL;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRARON SERVICIOS ASIGNADOS A LA PERSONA ' || P_ID_PERSONA);
    RETURN 0;
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL OBTENER SERVICIOS DE PERSONA: ' || SQLERRM);
    RETURN 0;
    END FIDE_TOTAL_SERVICIOS_PERSONA_FN;
    
    FUNCTION FIDE_TOTAL_TURNOS_GUARDIA_FN(P_ID_PERSONA NUMBER) RETURN NUMBER IS
    CURSOR_TURNOS SYS_REFCURSOR;
    V_TOTAL NUMBER := 0;
    BEGIN
    OPEN CURSOR_TURNOS FOR
    SELECT COUNT(*)
    FROM FIDE_TURNOS_TB
    WHERE ID_PERSONA = P_ID_PERSONA;
    FETCH CURSOR_TURNOS INTO V_TOTAL;
    CLOSE CURSOR_TURNOS;
    RETURN V_TOTAL;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRARON TURNOS PARA EL GUARDIA ' || P_ID_PERSONA);
    RETURN 0;
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL OBTENER TURNOS DEL GUARDIA: ' || SQLERRM);
    RETURN 0;
    END FIDE_TOTAL_TURNOS_GUARDIA_FN;
    
    FUNCTION FIDE_TOTAL_EVENTOS_TIPO_FN(P_ID_TIPO_EVENTO NUMBER) RETURN NUMBER IS
    CURSOR_EVENTOS SYS_REFCURSOR;
    V_TOTAL NUMBER := 0;
    BEGIN
    OPEN CURSOR_EVENTOS FOR
    SELECT COUNT(*)
    FROM FIDE_EVENTOS_TB
    WHERE ID_TIPO_EVENTO = P_ID_TIPO_EVENTO;
    FETCH CURSOR_EVENTOS INTO V_TOTAL;
    CLOSE CURSOR_EVENTOS;
    RETURN V_TOTAL;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRARON EVENTOS PARA EL TIPO ' || P_ID_TIPO_EVENTO);
    RETURN 0;
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL OBTENER EVENTOS POR TIPO: ' || SQLERRM);
    RETURN 0;
    END FIDE_TOTAL_EVENTOS_TIPO_FN;
    
    FUNCTION FIDE_TOTAL_RESIDENTES_RESIDENCIA_FN(P_ID_RESIDENCIA NUMBER) RETURN NUMBER IS
    CURSOR_RESIDENTES SYS_REFCURSOR;
    V_TOTAL NUMBER := 0;
    BEGIN
    OPEN CURSOR_RESIDENTES FOR
    SELECT COUNT(*)
    FROM FIDE_RESIDENTES_TB
    WHERE ID_RESIDENCIA = P_ID_RESIDENCIA;
    FETCH CURSOR_RESIDENTES INTO V_TOTAL;
    CLOSE CURSOR_RESIDENTES;
    RETURN V_TOTAL;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRARON RESIDENTES PARA LA RESIDENCIA ' || P_ID_RESIDENCIA);
    RETURN 0;
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL OBTENER RESIDENTES DE RESIDENCIA: ' || SQLERRM);
    RETURN 0;
    END FIDE_TOTAL_RESIDENTES_RESIDENCIA_FN;
    
    FUNCTION FIDE_TOTAL_CONSULTAS_PERSONA_FN(P_ID_PERSONA NUMBER) RETURN NUMBER IS
    CURSOR_CONSULTAS SYS_REFCURSOR;
    V_TOTAL NUMBER := 0;
    BEGIN
    OPEN CURSOR_CONSULTAS FOR
    SELECT COUNT(*)
    FROM FIDE_CONSULTAS_TB
    WHERE ID_PERSONA = P_ID_PERSONA;
    FETCH CURSOR_CONSULTAS INTO V_TOTAL;
    CLOSE CURSOR_CONSULTAS;
    RETURN V_TOTAL;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRARON CONSULTAS PARA LA PERSONA ' || P_ID_PERSONA);
    RETURN 0;
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL OBTENER CONSULTAS DE PERSONA: ' || SQLERRM);
    RETURN 0;
    END FIDE_TOTAL_CONSULTAS_PERSONA_FN;
    
    FUNCTION FIDE_TOTAL_REPORTES_PERSONA_FN(P_ID_PERSONA NUMBER) RETURN NUMBER IS
    CURSOR_REPORTES SYS_REFCURSOR;
    V_TOTAL NUMBER := 0;
    BEGIN
    OPEN CURSOR_REPORTES FOR
    SELECT COUNT(*)
    FROM FIDE_REPORTES_TB
    WHERE ID_PERSONA = P_ID_PERSONA;
    FETCH CURSOR_REPORTES INTO V_TOTAL;
    CLOSE CURSOR_REPORTES;
    RETURN V_TOTAL;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRARON REPORTES PARA LA PERSONA ' || P_ID_PERSONA);
    RETURN 0;
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL OBTENER REPORTES DE PERSONA: ' || SQLERRM);
    RETURN 0;
    END FIDE_TOTAL_REPORTES_PERSONA_FN;
    
    FUNCTION FIDE_TOTAL_FACTURAS_ESTADO_FN(P_ID_ESTADO NUMBER) RETURN NUMBER IS
    V_TOTAL NUMBER := 0;
    BEGIN
    FOR REG IN (
    SELECT COUNT(*) AS TOTAL
    FROM FIDE_FACTURAS_TB
    WHERE ID_ESTADO = P_ID_ESTADO
    ) LOOP
    V_TOTAL := REG.TOTAL;
    END LOOP;
    RETURN V_TOTAL;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRARON FACTURAS PARA EL ESTADO ' || P_ID_ESTADO);
    RETURN 0;
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL OBTENER FACTURAS POR ESTADO: ' || SQLERRM);
    RETURN 0;
    END FIDE_TOTAL_FACTURAS_ESTADO_FN;
    
    FUNCTION FIDE_TOTAL_FACTURAS_TIPO_PAGO_FN(P_ID_TIPO_PAGO NUMBER) RETURN NUMBER IS
    V_TOTAL NUMBER := 0;
    BEGIN
    FOR REG IN (
    SELECT COUNT(*) AS TOTAL
    FROM FIDE_FACTURAS_TB
    WHERE ID_TIPO_PAGO = P_ID_TIPO_PAGO
    ) LOOP
    V_TOTAL := REG.TOTAL;
    END LOOP;
    RETURN V_TOTAL;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRARON FACTURAS PARA EL TIPO DE PAGO ' || P_ID_TIPO_PAGO);
    RETURN 0;
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL OBTENER FACTURAS POR TIPO DE PAGO: ' || SQLERRM);
    RETURN 0;
    END FIDE_TOTAL_FACTURAS_TIPO_PAGO_FN;
    
    FUNCTION FIDE_TOTAL_FACTURAS_FORMA_PAGO_FN(P_ID_FORMA_PAGO NUMBER) RETURN NUMBER IS
    V_TOTAL NUMBER := 0;
    BEGIN
    FOR REG IN (
    SELECT COUNT(*) AS TOTAL
    FROM FIDE_FACTURAS_TB
    WHERE ID_FORMA_PAGO = P_ID_FORMA_PAGO
    ) LOOP
    V_TOTAL := REG.TOTAL;
    END LOOP;
    RETURN V_TOTAL;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRARON FACTURAS PARA LA FORMA DE PAGO ' || P_ID_FORMA_PAGO);
    RETURN 0;
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL OBTENER FACTURAS POR FORMA DE PAGO: ' || SQLERRM);
    RETURN 0;
    END FIDE_TOTAL_FACTURAS_FORMA_PAGO_FN;
    
    FUNCTION FIDE_TOTAL_SERVICIOS_TIPO_FN(P_ID_TIPO_SERVICIO NUMBER) RETURN NUMBER IS
    V_TOTAL NUMBER := 0;
    BEGIN
    FOR REG IN (
    SELECT COUNT(*) AS TOTAL
    FROM FIDE_SERVICIOS_TB
    WHERE ID_TIPO_SERVICIO = P_ID_TIPO_SERVICIO
    ) LOOP
    V_TOTAL := REG.TOTAL;
    END LOOP;
    RETURN V_TOTAL;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRARON SERVICIOS PARA EL TIPO ' || P_ID_TIPO_SERVICIO);
    RETURN 0;
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL OBTENER SERVICIOS POR TIPO: ' || SQLERRM);
    RETURN 0;
    END FIDE_TOTAL_SERVICIOS_TIPO_FN;
    
    PROCEDURE FIDE_ESTADOS_INSERTAR_SP(P_ID_ESTADO NUMBER, P_NOMBRE_ESTADO VARCHAR2) IS
    BEGIN
    INSERT INTO FIDE_ESTADOS_TB (ID_ESTADO, NOMBRE_ESTADO)
    VALUES (P_ID_ESTADO, P_NOMBRE_ESTADO);
    COMMIT;
    EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
    DBMS_OUTPUT.PUT_LINE('YA EXISTE UN ESTADO CON EL ID ' || P_ID_ESTADO);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR ESTADO: ' || SQLERRM);
    END FIDE_ESTADOS_INSERTAR_SP;
    
    PROCEDURE FIDE_ESTADOS_ACTUALIZAR_SP(P_ID_ESTADO NUMBER, P_NOMBRE_ESTADO VARCHAR2) IS
    BEGIN
    UPDATE FIDE_ESTADOS_TB
    SET NOMBRE_ESTADO = P_NOMBRE_ESTADO
    WHERE ID_ESTADO = P_ID_ESTADO;
    COMMIT;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL ESTADO CON ID ' || P_ID_ESTADO);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR ESTADO: ' || SQLERRM);
    END FIDE_ESTADOS_ACTUALIZAR_SP;
    
    PROCEDURE FIDE_ESTADOS_ELIMINAR_SP(P_ID_ESTADO NUMBER) IS
    BEGIN
    DELETE FROM FIDE_ESTADOS_TB
    WHERE ID_ESTADO = P_ID_ESTADO;
    COMMIT;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL ESTADO CON ID ' || P_ID_ESTADO);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR ESTADO: ' || SQLERRM);
    END FIDE_ESTADOS_ELIMINAR_SP;
    
    PROCEDURE FIDE_ROLES_INSERTAR_SP(P_ID_ROL NUMBER, P_ROL VARCHAR2, P_ID_ESTADO NUMBER) IS
    BEGIN
    INSERT INTO FIDE_ROLES_TB (ID_ROL, ROL, ID_ESTADO)
    VALUES (P_ID_ROL, P_ROL, P_ID_ESTADO);
    COMMIT;
    EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
    DBMS_OUTPUT.PUT_LINE('YA EXISTE UN ROL CON EL ID ' || P_ID_ROL);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR ROL: ' || SQLERRM);
    END FIDE_ROLES_INSERTAR_SP;
    
    PROCEDURE FIDE_ROLES_ACTUALIZAR_SP(P_ID_ROL NUMBER, P_ROL VARCHAR2, P_ID_ESTADO NUMBER) IS
    BEGIN
    UPDATE FIDE_ROLES_TB
    SET ROL = P_ROL,
    ID_ESTADO = P_ID_ESTADO
    WHERE ID_ROL = P_ID_ROL;
    COMMIT;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL ROL CON ID ' || P_ID_ROL);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR ROL: ' || SQLERRM);
    END FIDE_ROLES_ACTUALIZAR_SP;
    
    PROCEDURE FIDE_ROLES_ELIMINAR_SP(P_ID_ROL NUMBER) IS
    BEGIN
    UPDATE FIDE_ROLES_TB
    SET ID_ESTADO = 2
    WHERE ID_ROL = P_ID_ROL;
    COMMIT;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL ROL CON ID ' || P_ID_ROL);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR ROL: ' || SQLERRM);
    END FIDE_ROLES_ELIMINAR_SP;
    
    PROCEDURE FIDE_TIPOS_PAGO_INSERTAR_SP(P_ID_TIPO_PAGO NUMBER, P_TIPO VARCHAR2, P_ID_ESTADO NUMBER) IS
    BEGIN
    INSERT INTO FIDE_TIPOS_PAGO_TB (ID_TIPO_PAGO, TIPO, ID_ESTADO)
    VALUES (P_ID_TIPO_PAGO, P_TIPO, P_ID_ESTADO);
    COMMIT;
    EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
    DBMS_OUTPUT.PUT_LINE('YA EXISTE UN TIPO DE PAGO CON EL ID ' || P_ID_TIPO_PAGO);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR TIPO DE PAGO: ' || SQLERRM);
    END FIDE_TIPOS_PAGO_INSERTAR_SP;
    
    PROCEDURE FIDE_TIPOS_PAGO_ACTUALIZAR_SP(P_ID_TIPO_PAGO NUMBER, P_TIPO VARCHAR2, P_ID_ESTADO NUMBER) IS
    BEGIN
    UPDATE FIDE_TIPOS_PAGO_TB
    SET TIPO = P_TIPO,
    ID_ESTADO = P_ID_ESTADO
    WHERE ID_TIPO_PAGO = P_ID_TIPO_PAGO;
    COMMIT;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL TIPO DE PAGO CON ID ' || P_ID_TIPO_PAGO);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR TIPO DE PAGO: ' || SQLERRM);
    END FIDE_TIPOS_PAGO_ACTUALIZAR_SP;
    
    PROCEDURE FIDE_TIPOS_PAGO_ELIMINAR_SP(P_ID_TIPO_PAGO NUMBER) IS
    BEGIN
    UPDATE FIDE_TIPOS_PAGO_TB
    SET ID_ESTADO = 2
    WHERE ID_TIPO_PAGO = P_ID_TIPO_PAGO;
    COMMIT;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL TIPO DE PAGO CON ID ' || P_ID_TIPO_PAGO);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR TIPO DE PAGO: ' || SQLERRM);
    END FIDE_TIPOS_PAGO_ELIMINAR_SP;
    
    PROCEDURE FIDE_FORMAS_PAGOS_INSERTAR_SP(P_ID_FORMA_PAGO NUMBER, P_FORMA VARCHAR2, P_ID_ESTADO NUMBER) IS
    BEGIN
    INSERT INTO FIDE_FORMAS_PAGOS_TB (ID_FORMA_PAGO, FORMA, ID_ESTADO)
    VALUES (P_ID_FORMA_PAGO, P_FORMA, P_ID_ESTADO);
    COMMIT;
    EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
    DBMS_OUTPUT.PUT_LINE('YA EXISTE UNA FORMA DE PAGO CON EL ID ' || P_ID_FORMA_PAGO);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR FORMA DE PAGO: ' || SQLERRM);
    END FIDE_FORMAS_PAGOS_INSERTAR_SP;
    
    PROCEDURE FIDE_FORMAS_PAGOS_ACTUALIZAR_SP(P_ID_FORMA_PAGO NUMBER, P_FORMA VARCHAR2, P_ID_ESTADO NUMBER) IS
    BEGIN
    UPDATE FIDE_FORMAS_PAGOS_TB
    SET FORMA = P_FORMA,
    ID_ESTADO = P_ID_ESTADO
    WHERE ID_FORMA_PAGO = P_ID_FORMA_PAGO;
    COMMIT;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO LA FORMA DE PAGO CON ID ' || P_ID_FORMA_PAGO);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR FORMA DE PAGO: ' || SQLERRM);
    END FIDE_FORMAS_PAGOS_ACTUALIZAR_SP;
    
    PROCEDURE FIDE_FORMAS_PAGOS_ELIMINAR_SP(P_ID_FORMA_PAGO NUMBER) IS
    BEGIN
    UPDATE FIDE_FORMAS_PAGOS_TB
    SET ID_ESTADO = 2
    WHERE ID_FORMA_PAGO = P_ID_FORMA_PAGO;
    COMMIT;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO LA FORMA DE PAGO CON ID ' || P_ID_FORMA_PAGO);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR FORMA DE PAGO: ' || SQLERRM);
    END FIDE_FORMAS_PAGOS_ELIMINAR_SP;
    
    PROCEDURE FIDE_HORARIOS_TURNOS_INSERTAR_SP(P_ID_HORARIO NUMBER, P_HORARIO_TURNO VARCHAR2, P_ID_ESTADO NUMBER) IS
    BEGIN
    INSERT INTO FIDE_HORARIOS_TURNOS_TB (ID_HORARIO, HORARIO_TURNO, ID_ESTADO)
    VALUES (P_ID_HORARIO, P_HORARIO_TURNO, P_ID_ESTADO);
    COMMIT;
    EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
    DBMS_OUTPUT.PUT_LINE('YA EXISTE UN HORARIO CON EL ID ' || P_ID_HORARIO);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR HORARIO DE TURNO: ' || SQLERRM);
    END FIDE_HORARIOS_TURNOS_INSERTAR_SP;
    
    PROCEDURE FIDE_HORARIOS_TURNOS_ACTUALIZAR_SP(P_ID_HORARIO NUMBER, P_HORARIO_TURNO VARCHAR2, P_ID_ESTADO NUMBER) IS
    BEGIN
    UPDATE FIDE_HORARIOS_TURNOS_TB
    SET HORARIO_TURNO = P_HORARIO_TURNO,
    ID_ESTADO = P_ID_ESTADO
    WHERE ID_HORARIO = P_ID_HORARIO;
    COMMIT;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL HORARIO CON ID ' || P_ID_HORARIO);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR HORARIO DE TURNO: ' || SQLERRM);
    END FIDE_HORARIOS_TURNOS_ACTUALIZAR_SP;
    
    PROCEDURE FIDE_HORARIOS_TURNOS_ELIMINAR_SP(P_ID_HORARIO NUMBER) IS
    BEGIN
    UPDATE FIDE_HORARIOS_TURNOS_TB
    SET ID_ESTADO = 2
    WHERE ID_HORARIO = P_ID_HORARIO;
    COMMIT;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL HORARIO CON ID ' || P_ID_HORARIO);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR HORARIO DE TURNO: ' || SQLERRM);
    END FIDE_HORARIOS_TURNOS_ELIMINAR_SP;
    
    PROCEDURE FIDE_FECHAS_TURNOS_INSERTAR_SP(P_ID_FECHAS NUMBER, P_FECHAS_TURNO DATE, P_ID_ESTADO NUMBER) IS
    BEGIN
    INSERT INTO FIDE_FECHAS_TURNOS_TB (ID_FECHAS, FECHAS_TURNO, ID_ESTADO)
    VALUES (P_ID_FECHAS, P_FECHAS_TURNO, P_ID_ESTADO);
    COMMIT;
    EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
    DBMS_OUTPUT.PUT_LINE('YA EXISTE UNA FECHA DE TURNO CON EL ID ' || P_ID_FECHAS);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR FECHA DE TURNO: ' || SQLERRM);
    END FIDE_FECHAS_TURNOS_INSERTAR_SP;
    
    PROCEDURE FIDE_FECHAS_TURNOS_ACTUALIZAR_SP(P_ID_FECHAS NUMBER, P_FECHAS_TURNO DATE, P_ID_ESTADO NUMBER) IS
    BEGIN
    UPDATE FIDE_FECHAS_TURNOS_TB
    SET FECHAS_TURNO = P_FECHAS_TURNO,
    ID_ESTADO = P_ID_ESTADO
    WHERE ID_FECHAS = P_ID_FECHAS;
    COMMIT;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO LA FECHA DE TURNO CON ID ' || P_ID_FECHAS);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR FECHA DE TURNO: ' || SQLERRM);
    END FIDE_FECHAS_TURNOS_ACTUALIZAR_SP;
    
    PROCEDURE FIDE_FECHAS_TURNOS_ELIMINAR_SP(P_ID_FECHAS NUMBER) IS
    BEGIN
    UPDATE FIDE_FECHAS_TURNOS_TB
    SET ID_ESTADO = 2
    WHERE ID_FECHAS = P_ID_FECHAS;
    COMMIT;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO LA FECHA DE TURNO CON ID ' || P_ID_FECHAS);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR FECHA DE TURNO: ' || SQLERRM);
    END FIDE_FECHAS_TURNOS_ELIMINAR_SP;
    
    PROCEDURE FIDE_TIPOS_ESPACIOS_INSERTAR_SP(P_ID_TIPO_ESPACIO NUMBER, P_NOMBRE_ESPACIO VARCHAR2, P_DESCR_ESPACIO VARCHAR2, P_ID_ESTADO NUMBER) IS
    BEGIN
    INSERT INTO FIDE_TIPOS_ESPACIOS_TB (ID_TIPO_ESPACIO, NOMBRE_ESPACIO, DESCR_ESPACIO, ID_ESTADO)
    VALUES (P_ID_TIPO_ESPACIO, P_NOMBRE_ESPACIO, P_DESCR_ESPACIO, P_ID_ESTADO);
    COMMIT;
    EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
    DBMS_OUTPUT.PUT_LINE('YA EXISTE UN TIPO DE ESPACIO CON EL ID ' || P_ID_TIPO_ESPACIO);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR TIPO DE ESPACIO: ' || SQLERRM);
    END FIDE_TIPOS_ESPACIOS_INSERTAR_SP;
    
    PROCEDURE FIDE_TIPOS_ESPACIOS_ACTUALIZAR_SP(P_ID_TIPO_ESPACIO NUMBER, P_NOMBRE_ESPACIO VARCHAR2, P_DESCR_ESPACIO VARCHAR2, P_ID_ESTADO NUMBER) IS
    BEGIN
    UPDATE FIDE_TIPOS_ESPACIOS_TB
    SET NOMBRE_ESPACIO = P_NOMBRE_ESPACIO,
    DESCR_ESPACIO = P_DESCR_ESPACIO,
    ID_ESTADO = P_ID_ESTADO
    WHERE ID_TIPO_ESPACIO = P_ID_TIPO_ESPACIO;
    COMMIT;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL TIPO DE ESPACIO CON ID ' || P_ID_TIPO_ESPACIO);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR TIPO DE ESPACIO: ' || SQLERRM);
    END FIDE_TIPOS_ESPACIOS_ACTUALIZAR_SP;
    
    PROCEDURE FIDE_TIPOS_ESPACIOS_ELIMINAR_SP(P_ID_TIPO_ESPACIO NUMBER) IS
    BEGIN
    UPDATE FIDE_TIPOS_ESPACIOS_TB
    SET ID_ESTADO = 2
    WHERE ID_TIPO_ESPACIO = P_ID_TIPO_ESPACIO;
    COMMIT;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL TIPO DE ESPACIO CON ID ' || P_ID_TIPO_ESPACIO);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR TIPO DE ESPACIO: ' || SQLERRM);
    END FIDE_TIPOS_ESPACIOS_ELIMINAR_SP;
    
    PROCEDURE FIDE_TIPOS_EVENTOS_INSERTAR_SP(P_ID_TIPO_EVENTO NUMBER, P_TIPO_EVENTO VARCHAR2, P_ID_ESTADO NUMBER) IS
    BEGIN
    INSERT INTO FIDE_TIPOS_EVENTOS_TB (ID_TIPO_EVENTO, TIPO_EVENTO, ID_ESTADO)
    VALUES (P_ID_TIPO_EVENTO, P_TIPO_EVENTO, P_ID_ESTADO);
    COMMIT;
    EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
    DBMS_OUTPUT.PUT_LINE('YA EXISTE UN TIPO DE EVENTO CON EL ID ' || P_ID_TIPO_EVENTO);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR TIPO DE EVENTO: ' || SQLERRM);
    END FIDE_TIPOS_EVENTOS_INSERTAR_SP;
    
    PROCEDURE FIDE_TIPOS_EVENTOS_ACTUALIZAR_SP(P_ID_TIPO_EVENTO NUMBER, P_TIPO_EVENTO VARCHAR2, P_ID_ESTADO NUMBER) IS
    BEGIN
    UPDATE FIDE_TIPOS_EVENTOS_TB
    SET TIPO_EVENTO = P_TIPO_EVENTO,
    ID_ESTADO = P_ID_ESTADO
    WHERE ID_TIPO_EVENTO = P_ID_TIPO_EVENTO;
    COMMIT;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL TIPO DE EVENTO CON ID ' || P_ID_TIPO_EVENTO);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR TIPO DE EVENTO: ' || SQLERRM);
    END FIDE_TIPOS_EVENTOS_ACTUALIZAR_SP;
    
    PROCEDURE FIDE_TIPOS_EVENTOS_ELIMINAR_SP(P_ID_TIPO_EVENTO NUMBER) IS
    BEGIN
    UPDATE FIDE_TIPOS_EVENTOS_TB
    SET ID_ESTADO = 2
    WHERE ID_TIPO_EVENTO = P_ID_TIPO_EVENTO;
    COMMIT;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL TIPO DE EVENTO CON ID ' || P_ID_TIPO_EVENTO);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR TIPO DE EVENTO: ' || SQLERRM);
    END FIDE_TIPOS_EVENTOS_ELIMINAR_SP;
    
    PROCEDURE FIDE_TIPOS_SERVICIOS_INSERTAR_SP(P_ID_TIPO_SERVICIO NUMBER, P_TIPO_SERVICIO VARCHAR2, P_ID_ESTADO NUMBER) IS
    BEGIN
    INSERT INTO FIDE_TIPOS_SERVICIOS_TB (ID_TIPO_SERVICIO, TIPO_SERVICIO, ID_ESTADO)
    VALUES (P_ID_TIPO_SERVICIO, P_TIPO_SERVICIO, P_ID_ESTADO);
    COMMIT;
    EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
    DBMS_OUTPUT.PUT_LINE('YA EXISTE UN TIPO DE SERVICIO CON EL ID ' || P_ID_TIPO_SERVICIO);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR TIPO DE SERVICIO: ' || SQLERRM);
    END FIDE_TIPOS_SERVICIOS_INSERTAR_SP;
    
    PROCEDURE FIDE_TIPOS_SERVICIOS_ACTUALIZAR_SP(P_ID_TIPO_SERVICIO NUMBER, P_TIPO_SERVICIO VARCHAR2, P_ID_ESTADO NUMBER) IS
    BEGIN
    UPDATE FIDE_TIPOS_SERVICIOS_TB
    SET TIPO_SERVICIO = P_TIPO_SERVICIO,
    ID_ESTADO = P_ID_ESTADO
    WHERE ID_TIPO_SERVICIO = P_ID_TIPO_SERVICIO;
    COMMIT;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL TIPO DE SERVICIO CON ID ' || P_ID_TIPO_SERVICIO);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR TIPO DE SERVICIO: ' || SQLERRM);
    END FIDE_TIPOS_SERVICIOS_ACTUALIZAR_SP;
    
    PROCEDURE FIDE_TIPOS_SERVICIOS_ELIMINAR_SP(P_ID_TIPO_SERVICIO NUMBER) IS
    BEGIN
    UPDATE FIDE_TIPOS_SERVICIOS_TB
    SET ID_ESTADO = 2
    WHERE ID_TIPO_SERVICIO = P_ID_TIPO_SERVICIO;
    COMMIT;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL TIPO DE SERVICIO CON ID ' || P_ID_TIPO_SERVICIO);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR TIPO DE SERVICIO: ' || SQLERRM);
    END FIDE_TIPOS_SERVICIOS_ELIMINAR_SP;
    
    PROCEDURE FIDE_PERSONAS_INSERTAR_SP(P_ID_PERSONA NUMBER, P_NOMBRE VARCHAR2, P_APELLIDO_PATERNO VARCHAR2, P_APELLIDO_MATERNO VARCHAR2, P_FECHA_REGISTRO DATE, P_ID_ROL NUMBER, P_ID_ESTADO NUMBER) IS
    BEGIN
    INSERT INTO FIDE_PERSONAS_TB (ID_PERSONA, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_REGISTRO, ID_ROL, ID_ESTADO)
    VALUES (P_ID_PERSONA, P_NOMBRE, P_APELLIDO_PATERNO, P_APELLIDO_MATERNO, P_FECHA_REGISTRO, P_ID_ROL, P_ID_ESTADO);
    COMMIT;
    EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
    DBMS_OUTPUT.PUT_LINE('YA EXISTE UNA PERSONA CON LA CEDULA ' || P_ID_PERSONA);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR PERSONA: ' || SQLERRM);
    END FIDE_PERSONAS_INSERTAR_SP;
    
    PROCEDURE FIDE_PERSONAS_ACTUALIZAR_SP(P_ID_PERSONA NUMBER, P_NOMBRE VARCHAR2, P_APELLIDO_PATERNO VARCHAR2, P_APELLIDO_MATERNO VARCHAR2, P_FECHA_REGISTRO DATE, P_ID_ROL NUMBER, P_ID_ESTADO NUMBER) IS
    BEGIN
    UPDATE FIDE_PERSONAS_TB
    SET NOMBRE = P_NOMBRE,
    APELLIDO_PATERNO = P_APELLIDO_PATERNO,
    APELLIDO_MATERNO = P_APELLIDO_MATERNO,
    FECHA_REGISTRO = P_FECHA_REGISTRO,
    ID_ROL = P_ID_ROL,
    ID_ESTADO = P_ID_ESTADO
    WHERE ID_PERSONA = P_ID_PERSONA;
    COMMIT;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO LA PERSONA CON CEDULA ' || P_ID_PERSONA);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR PERSONA: ' || SQLERRM);
    END FIDE_PERSONAS_ACTUALIZAR_SP;
    
    PROCEDURE FIDE_PERSONAS_ELIMINAR_SP(P_ID_PERSONA NUMBER) IS
    BEGIN
    UPDATE FIDE_PERSONAS_TB
    SET ID_ESTADO = 2
    WHERE ID_PERSONA = P_ID_PERSONA;
    COMMIT;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO LA PERSONA CON CEDULA ' || P_ID_PERSONA);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR PERSONA: ' || SQLERRM);
    END FIDE_PERSONAS_ELIMINAR_SP;
    
    PROCEDURE FIDE_TELEFONOS_INSERTAR_SP(P_ID_TELEFONO NUMBER, P_ID_PERSONA NUMBER, P_TELEFONO VARCHAR2, P_ID_ESTADO NUMBER) IS
    BEGIN
    INSERT INTO FIDE_TELEFONOS_TB (ID_TELEFONO, ID_PERSONA, TELEFONO, ID_ESTADO)
    VALUES (P_ID_TELEFONO, P_ID_PERSONA, P_TELEFONO, P_ID_ESTADO);
    COMMIT;
    EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
    DBMS_OUTPUT.PUT_LINE('YA EXISTE UN TELEFONO CON EL ID ' || P_ID_TELEFONO);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR TELEFONO: ' || SQLERRM);
    END FIDE_TELEFONOS_INSERTAR_SP;
    
    PROCEDURE FIDE_TELEFONOS_ACTUALIZAR_SP(P_ID_TELEFONO NUMBER, P_ID_PERSONA NUMBER, P_TELEFONO VARCHAR2, P_ID_ESTADO NUMBER) IS
    BEGIN
    UPDATE FIDE_TELEFONOS_TB
    SET ID_PERSONA = P_ID_PERSONA,
    TELEFONO = P_TELEFONO,
    ID_ESTADO = P_ID_ESTADO
    WHERE ID_TELEFONO = P_ID_TELEFONO;
    COMMIT;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL TELEFONO CON ID ' || P_ID_TELEFONO);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR TELEFONO: ' || SQLERRM);
    END FIDE_TELEFONOS_ACTUALIZAR_SP;
    
    PROCEDURE FIDE_TELEFONOS_ELIMINAR_SP(P_ID_TELEFONO NUMBER) IS
    BEGIN
    UPDATE FIDE_TELEFONOS_TB
    SET ID_ESTADO = 2
    WHERE ID_TELEFONO = P_ID_TELEFONO;
    COMMIT;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL TELEFONO CON ID ' || P_ID_TELEFONO);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR TELEFONO: ' || SQLERRM);
    END FIDE_TELEFONOS_ELIMINAR_SP;
    
    PROCEDURE FIDE_CORREOS_INSERTAR_SP(P_ID_CORREO NUMBER, P_ID_PERSONA NUMBER, P_CORREO VARCHAR2, P_ID_ESTADO NUMBER) IS
    BEGIN
    INSERT INTO FIDE_CORREOS_TB (ID_CORREO, ID_PERSONA, CORREO, ID_ESTADO)
    VALUES (P_ID_CORREO, P_ID_PERSONA, P_CORREO, P_ID_ESTADO);
    COMMIT;
    EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
    DBMS_OUTPUT.PUT_LINE('YA EXISTE UN CORREO CON EL ID ' || P_ID_CORREO);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR CORREO: ' || SQLERRM);
    END FIDE_CORREOS_INSERTAR_SP;
    
    PROCEDURE FIDE_CORREOS_ACTUALIZAR_SP(P_ID_CORREO NUMBER, P_ID_PERSONA NUMBER, P_CORREO VARCHAR2, P_ID_ESTADO NUMBER) IS
    BEGIN
    UPDATE FIDE_CORREOS_TB
    SET ID_PERSONA = P_ID_PERSONA,
    CORREO = P_CORREO,
    ID_ESTADO = P_ID_ESTADO
    WHERE ID_CORREO = P_ID_CORREO;
    COMMIT;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL CORREO CON ID ' || P_ID_CORREO);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR CORREO: ' || SQLERRM);
    END FIDE_CORREOS_ACTUALIZAR_SP;
    
    PROCEDURE FIDE_CORREOS_ELIMINAR_SP(P_ID_CORREO NUMBER) IS
    BEGIN
    UPDATE FIDE_CORREOS_TB
    SET ID_ESTADO = 2
    WHERE ID_CORREO = P_ID_CORREO;
    COMMIT;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL CORREO CON ID ' || P_ID_CORREO);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR CORREO: ' || SQLERRM);
    END FIDE_CORREOS_ELIMINAR_SP;
    
    PROCEDURE FIDE_RESIDENCIAS_INSERTAR_SP(P_ID_RESIDENCIA NUMBER, P_MONTO_ALQUILER NUMBER, P_MONTO_MANTENIMIENTO NUMBER, P_ID_TIPO_PAGO NUMBER, P_ID_ESTADO NUMBER) IS
    BEGIN
    INSERT INTO FIDE_RESIDENCIAS_TB (ID_RESIDENCIA, MONTO_ALQUILER, MONTO_MANTENIMIENTO, ID_TIPO_PAGO, ID_ESTADO)
    VALUES (P_ID_RESIDENCIA, P_MONTO_ALQUILER, P_MONTO_MANTENIMIENTO, P_ID_TIPO_PAGO, P_ID_ESTADO);
    COMMIT;
    EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
    DBMS_OUTPUT.PUT_LINE('YA EXISTE UNA RESIDENCIA CON EL ID ' || P_ID_RESIDENCIA);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR RESIDENCIA: ' || SQLERRM);
    END FIDE_RESIDENCIAS_INSERTAR_SP;
    
    PROCEDURE FIDE_RESIDENCIAS_ACTUALIZAR_SP(P_ID_RESIDENCIA NUMBER, P_MONTO_ALQUILER NUMBER, P_MONTO_MANTENIMIENTO NUMBER, P_ID_TIPO_PAGO NUMBER, P_ID_ESTADO NUMBER) IS
    BEGIN
    UPDATE FIDE_RESIDENCIAS_TB
    SET MONTO_ALQUILER = P_MONTO_ALQUILER,
    MONTO_MANTENIMIENTO = P_MONTO_MANTENIMIENTO,
    ID_TIPO_PAGO = P_ID_TIPO_PAGO,
    ID_ESTADO = P_ID_ESTADO
    WHERE ID_RESIDENCIA = P_ID_RESIDENCIA;
    COMMIT;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO LA RESIDENCIA CON ID ' || P_ID_RESIDENCIA);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR RESIDENCIA: ' || SQLERRM);
    END FIDE_RESIDENCIAS_ACTUALIZAR_SP;
    
    PROCEDURE FIDE_RESIDENCIAS_ELIMINAR_SP(P_ID_RESIDENCIA NUMBER) IS
    BEGIN
    UPDATE FIDE_RESIDENCIAS_TB
    SET ID_ESTADO = 2
    WHERE ID_RESIDENCIA = P_ID_RESIDENCIA;
    COMMIT;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO LA RESIDENCIA CON ID ' || P_ID_RESIDENCIA);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR RESIDENCIA: ' || SQLERRM);
    END FIDE_RESIDENCIAS_ELIMINAR_SP;
    
    PROCEDURE FIDE_RESIDENTES_INSERTAR_SP(P_ID_PERSONA NUMBER, P_ID_RESIDENCIA NUMBER, P_ID_ESTADO NUMBER) IS
    BEGIN
    INSERT INTO FIDE_RESIDENTES_TB (ID_PERSONA, ID_RESIDENCIA, ID_ESTADO)
    VALUES (P_ID_PERSONA, P_ID_RESIDENCIA, P_ID_ESTADO);
    COMMIT;
    EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
    DBMS_OUTPUT.PUT_LINE('LA PERSONA ' || P_ID_PERSONA || ' YA ESTA REGISTRADA EN LA RESIDENCIA ' || P_ID_RESIDENCIA);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR RESIDENTE: ' || SQLERRM);
    END FIDE_RESIDENTES_INSERTAR_SP;
    
    PROCEDURE FIDE_RESIDENTES_ACTUALIZAR_SP(P_ID_PERSONA NUMBER, P_ID_RESIDENCIA NUMBER, P_ID_ESTADO NUMBER) IS
    BEGIN
    UPDATE FIDE_RESIDENTES_TB
    SET ID_ESTADO = P_ID_ESTADO
    WHERE ID_PERSONA = P_ID_PERSONA
    AND ID_RESIDENCIA = P_ID_RESIDENCIA;
    COMMIT;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL RESIDENTE ' || P_ID_PERSONA || ' EN LA RESIDENCIA ' || P_ID_RESIDENCIA);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR RESIDENTE: ' || SQLERRM);
    END FIDE_RESIDENTES_ACTUALIZAR_SP;
    
    PROCEDURE FIDE_RESIDENTES_ELIMINAR_SP(P_ID_PERSONA NUMBER, P_ID_RESIDENCIA NUMBER) IS
    BEGIN
    UPDATE FIDE_RESIDENTES_TB
    SET ID_ESTADO = 2
    WHERE ID_PERSONA = P_ID_PERSONA
    AND ID_RESIDENCIA = P_ID_RESIDENCIA;
    COMMIT;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL RESIDENTE ' || P_ID_PERSONA || ' EN LA RESIDENCIA ' || P_ID_RESIDENCIA);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR RESIDENTE: ' || SQLERRM);
    END FIDE_RESIDENTES_ELIMINAR_SP;
    
    PROCEDURE FIDE_EVENTOS_INSERTAR_SP(P_ID_EVENTO NUMBER, P_DESCR_EVENTO VARCHAR2, P_FECHA_EVENTO DATE, P_ID_TIPO_EVENTO NUMBER, P_ID_TIPO_ESPACIO NUMBER, P_ID_ESTADO NUMBER) IS
    BEGIN
    INSERT INTO FIDE_EVENTOS_TB (ID_EVENTO, DESCR_EVENTO, FECHA_EVENTO, ID_TIPO_EVENTO, ID_TIPO_ESPACIO, ID_ESTADO)
    VALUES (P_ID_EVENTO, P_DESCR_EVENTO, P_FECHA_EVENTO, P_ID_TIPO_EVENTO, P_ID_TIPO_ESPACIO, P_ID_ESTADO);
    COMMIT;
    EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
    DBMS_OUTPUT.PUT_LINE('YA EXISTE UN EVENTO CON EL ID ' || P_ID_EVENTO);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR EVENTO: ' || SQLERRM);
    END FIDE_EVENTOS_INSERTAR_SP;
    
    PROCEDURE FIDE_EVENTOS_ACTUALIZAR_SP(P_ID_EVENTO NUMBER, P_DESCR_EVENTO VARCHAR2, P_FECHA_EVENTO DATE, P_ID_TIPO_EVENTO NUMBER, P_ID_TIPO_ESPACIO NUMBER, P_ID_ESTADO NUMBER) IS
    BEGIN
    UPDATE FIDE_EVENTOS_TB
    SET DESCR_EVENTO = P_DESCR_EVENTO,
    FECHA_EVENTO = P_FECHA_EVENTO,
    ID_TIPO_EVENTO = P_ID_TIPO_EVENTO,
    ID_TIPO_ESPACIO = P_ID_TIPO_ESPACIO,
    ID_ESTADO = P_ID_ESTADO
    WHERE ID_EVENTO = P_ID_EVENTO;
    COMMIT;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL EVENTO CON ID ' || P_ID_EVENTO);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR EVENTO: ' || SQLERRM);
    END FIDE_EVENTOS_ACTUALIZAR_SP;
    
    PROCEDURE FIDE_EVENTOS_ELIMINAR_SP(P_ID_EVENTO NUMBER) IS
    BEGIN
    UPDATE FIDE_EVENTOS_TB
    SET ID_ESTADO = 2
    WHERE ID_EVENTO = P_ID_EVENTO;
    COMMIT;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL EVENTO CON ID ' || P_ID_EVENTO);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR EVENTO: ' || SQLERRM);
    END FIDE_EVENTOS_ELIMINAR_SP;
    
    PROCEDURE FIDE_VEHICULOS_INSERTAR_SP(P_PLACA VARCHAR2, P_DESCRIPCION VARCHAR2, P_ID_TIPO_ESPACIO NUMBER, P_ID_PERSONA NUMBER, P_ID_ESTADO NUMBER) IS
    BEGIN
    INSERT INTO FIDE_VEHICULOS_TB (PLACA, DESCRIPCION, ID_TIPO_ESPACIO, ID_PERSONA, ID_ESTADO)
    VALUES (P_PLACA, P_DESCRIPCION, P_ID_TIPO_ESPACIO, P_ID_PERSONA, P_ID_ESTADO);
    COMMIT;
    EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
    DBMS_OUTPUT.PUT_LINE('YA EXISTE UN VEHICULO CON LA PLACA ' || P_PLACA);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR VEHICULO: ' || SQLERRM);
    END FIDE_VEHICULOS_INSERTAR_SP;
    
    PROCEDURE FIDE_VEHICULOS_ACTUALIZAR_SP(P_PLACA VARCHAR2, P_DESCRIPCION VARCHAR2, P_ID_TIPO_ESPACIO NUMBER, P_ID_PERSONA NUMBER, P_ID_ESTADO NUMBER) IS
    BEGIN
    UPDATE FIDE_VEHICULOS_TB
    SET DESCRIPCION = P_DESCRIPCION,
    ID_TIPO_ESPACIO = P_ID_TIPO_ESPACIO,
    ID_PERSONA = P_ID_PERSONA,
    ID_ESTADO = P_ID_ESTADO
    WHERE PLACA = P_PLACA;
    COMMIT;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL VEHICULO CON PLACA ' || P_PLACA);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR VEHICULO: ' || SQLERRM);
    END FIDE_VEHICULOS_ACTUALIZAR_SP;
    
    PROCEDURE FIDE_VEHICULOS_ELIMINAR_SP(P_PLACA VARCHAR2) IS
    BEGIN
    UPDATE FIDE_VEHICULOS_TB
    SET ID_ESTADO = 2
    WHERE PLACA = P_PLACA;
    COMMIT;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL VEHICULO CON PLACA ' || P_PLACA);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR VEHICULO: ' || SQLERRM);
    END FIDE_VEHICULOS_ELIMINAR_SP;
    
    PROCEDURE FIDE_SERVICIOS_INSERTAR_SP(P_ID_SERVICIO NUMBER, P_DESCR_SERVICIO VARCHAR2, P_FECHA_SALIDA DATE, P_ID_TIPO_SERVICIO NUMBER, P_ID_TIPO_EVENTO NUMBER, P_ID_ESTADO NUMBER) IS
    BEGIN
    INSERT INTO FIDE_SERVICIOS_TB (ID_SERVICIO, DESCR_SERVICIO, FECHA_SALIDA, ID_TIPO_SERVICIO, ID_TIPO_EVENTO, ID_ESTADO)
    VALUES (P_ID_SERVICIO, P_DESCR_SERVICIO, P_FECHA_SALIDA, P_ID_TIPO_SERVICIO, P_ID_TIPO_EVENTO, P_ID_ESTADO);
    COMMIT;
    EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
    DBMS_OUTPUT.PUT_LINE('YA EXISTE UN SERVICIO CON EL ID ' || P_ID_SERVICIO);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR SERVICIO: ' || SQLERRM);
    END FIDE_SERVICIOS_INSERTAR_SP;
    
    PROCEDURE FIDE_SERVICIOS_ACTUALIZAR_SP(P_ID_SERVICIO NUMBER, P_DESCR_SERVICIO VARCHAR2, P_FECHA_SALIDA DATE, P_ID_TIPO_SERVICIO NUMBER, P_ID_TIPO_EVENTO NUMBER, P_ID_ESTADO NUMBER) IS
    BEGIN
    UPDATE FIDE_SERVICIOS_TB
    SET DESCR_SERVICIO = P_DESCR_SERVICIO,
    FECHA_SALIDA = P_FECHA_SALIDA,
    ID_TIPO_SERVICIO = P_ID_TIPO_SERVICIO,
    ID_TIPO_EVENTO = P_ID_TIPO_EVENTO,
    ID_ESTADO = P_ID_ESTADO
    WHERE ID_SERVICIO = P_ID_SERVICIO;
    COMMIT;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL SERVICIO CON ID ' || P_ID_SERVICIO);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR SERVICIO: ' || SQLERRM);
    END FIDE_SERVICIOS_ACTUALIZAR_SP;
    
    PROCEDURE FIDE_SERVICIOS_ELIMINAR_SP(P_ID_SERVICIO NUMBER) IS
    BEGIN
    UPDATE FIDE_SERVICIOS_TB
    SET ID_ESTADO = 2
    WHERE ID_SERVICIO = P_ID_SERVICIO;
    COMMIT;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL SERVICIO CON ID ' || P_ID_SERVICIO);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR SERVICIO: ' || SQLERRM);
    END FIDE_SERVICIOS_ELIMINAR_SP;
    
    PROCEDURE FIDE_FACTURAS_INSERTAR_SP(P_ID_FACTURA NUMBER, P_FECHA_FACTURA DATE, P_DESCR_FACTURA VARCHAR2, P_ID_TIPO_PAGO NUMBER, P_ID_FORMA_PAGO NUMBER, P_ID_PERSONA NUMBER, P_ID_ESTADO NUMBER) IS
    BEGIN
    INSERT INTO FIDE_FACTURAS_TB (ID_FACTURA, FECHA_FACTURA, DESCR_FACTURA, ID_TIPO_PAGO, ID_FORMA_PAGO, ID_PERSONA, ID_ESTADO)
    VALUES (P_ID_FACTURA, P_FECHA_FACTURA, P_DESCR_FACTURA, P_ID_TIPO_PAGO, P_ID_FORMA_PAGO, P_ID_PERSONA, P_ID_ESTADO);
    COMMIT;
    EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
    DBMS_OUTPUT.PUT_LINE('YA EXISTE UNA FACTURA CON EL ID ' || P_ID_FACTURA);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR FACTURA: ' || SQLERRM);
    END FIDE_FACTURAS_INSERTAR_SP;
    
    PROCEDURE FIDE_FACTURAS_ACTUALIZAR_SP(P_ID_FACTURA NUMBER, P_FECHA_FACTURA DATE, P_DESCR_FACTURA VARCHAR2, P_ID_TIPO_PAGO NUMBER, P_ID_FORMA_PAGO NUMBER, P_ID_PERSONA NUMBER, P_ID_ESTADO NUMBER) IS
    BEGIN
    UPDATE FIDE_FACTURAS_TB
    SET FECHA_FACTURA = P_FECHA_FACTURA,
    DESCR_FACTURA = P_DESCR_FACTURA,
    ID_TIPO_PAGO = P_ID_TIPO_PAGO,
    ID_FORMA_PAGO = P_ID_FORMA_PAGO,
    ID_PERSONA = P_ID_PERSONA,
    ID_ESTADO = P_ID_ESTADO
    WHERE ID_FACTURA = P_ID_FACTURA;
    COMMIT;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO LA FACTURA CON ID ' || P_ID_FACTURA);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR FACTURA: ' || SQLERRM);
    END FIDE_FACTURAS_ACTUALIZAR_SP;
    
    PROCEDURE FIDE_FACTURAS_ELIMINAR_SP(P_ID_FACTURA NUMBER) IS
    BEGIN
    UPDATE FIDE_FACTURAS_TB
    SET ID_ESTADO = 2
    WHERE ID_FACTURA = P_ID_FACTURA;
    COMMIT;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO LA FACTURA CON ID ' || P_ID_FACTURA);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR FACTURA: ' || SQLERRM);
    END FIDE_FACTURAS_ELIMINAR_SP;
    
    PROCEDURE FIDE_CONSULTAS_INSERTAR_SP(P_ID_CONSULTA NUMBER, P_CONSULTA VARCHAR2, P_FECHA_CONSULTA DATE, P_ID_PERSONA NUMBER, P_ID_ESTADO NUMBER) IS
    BEGIN
    INSERT INTO FIDE_CONSULTAS_TB (ID_CONSULTA, CONSULTA, FECHA_CONSULTA, ID_PERSONA, ID_ESTADO)
    VALUES (P_ID_CONSULTA, P_CONSULTA, P_FECHA_CONSULTA, P_ID_PERSONA, P_ID_ESTADO);
    COMMIT;
    EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
    DBMS_OUTPUT.PUT_LINE('YA EXISTE UNA CONSULTA CON EL ID ' || P_ID_CONSULTA);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR CONSULTA: ' || SQLERRM);
    END FIDE_CONSULTAS_INSERTAR_SP;
    
    PROCEDURE FIDE_CONSULTAS_ACTUALIZAR_SP(P_ID_CONSULTA NUMBER, P_CONSULTA VARCHAR2, P_FECHA_CONSULTA DATE, P_ID_PERSONA NUMBER, P_ID_ESTADO NUMBER) IS
    BEGIN
    UPDATE FIDE_CONSULTAS_TB
    SET CONSULTA = P_CONSULTA,
    FECHA_CONSULTA = P_FECHA_CONSULTA,
    ID_PERSONA = P_ID_PERSONA,
    ID_ESTADO = P_ID_ESTADO
    WHERE ID_CONSULTA = P_ID_CONSULTA;
    COMMIT;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO LA CONSULTA CON ID ' || P_ID_CONSULTA);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR CONSULTA: ' || SQLERRM);
    END FIDE_CONSULTAS_ACTUALIZAR_SP;
    
    PROCEDURE FIDE_CONSULTAS_ELIMINAR_SP(P_ID_CONSULTA NUMBER) IS
    BEGIN
    UPDATE FIDE_CONSULTAS_TB
    SET ID_ESTADO = 2
    WHERE ID_CONSULTA = P_ID_CONSULTA;
    COMMIT;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO LA CONSULTA CON ID ' || P_ID_CONSULTA);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR CONSULTA: ' || SQLERRM);
    END FIDE_CONSULTAS_ELIMINAR_SP;
    
    PROCEDURE FIDE_REPORTES_INSERTAR_SP(P_ID_REPORTE NUMBER, P_REPORTE VARCHAR2, P_FECHA_REPORTE DATE, P_ID_PERSONA NUMBER, P_ID_ESTADO NUMBER) IS
    BEGIN
    INSERT INTO FIDE_REPORTES_TB (ID_REPORTE, REPORTE, FECHA_REPORTE, ID_PERSONA, ID_ESTADO)
    VALUES (P_ID_REPORTE, P_REPORTE, P_FECHA_REPORTE, P_ID_PERSONA, P_ID_ESTADO);
    COMMIT;
    EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
    DBMS_OUTPUT.PUT_LINE('YA EXISTE UN REPORTE CON EL ID ' || P_ID_REPORTE);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR REPORTE: ' || SQLERRM);
    END FIDE_REPORTES_INSERTAR_SP;
    
    PROCEDURE FIDE_REPORTES_ACTUALIZAR_SP(P_ID_REPORTE NUMBER, P_REPORTE VARCHAR2, P_FECHA_REPORTE DATE, P_ID_PERSONA NUMBER, P_ID_ESTADO NUMBER) IS
    BEGIN
    UPDATE FIDE_REPORTES_TB
    SET REPORTE = P_REPORTE,
    FECHA_REPORTE = P_FECHA_REPORTE,
    ID_PERSONA = P_ID_PERSONA,
    ID_ESTADO = P_ID_ESTADO
    WHERE ID_REPORTE = P_ID_REPORTE;
    COMMIT;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL REPORTE CON ID ' || P_ID_REPORTE);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR REPORTE: ' || SQLERRM);
    END FIDE_REPORTES_ACTUALIZAR_SP;
    
    PROCEDURE FIDE_REPORTES_ELIMINAR_SP(P_ID_REPORTE NUMBER) IS
    BEGIN
    UPDATE FIDE_REPORTES_TB
    SET ID_ESTADO = 2
    WHERE ID_REPORTE = P_ID_REPORTE;
    COMMIT;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL REPORTE CON ID ' || P_ID_REPORTE);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR REPORTE: ' || SQLERRM);
    END FIDE_REPORTES_ELIMINAR_SP;
    
    PROCEDURE FIDE_SALARIOS_INSERTAR_SP(P_ID_PERSONA NUMBER, P_MONTO NUMBER, P_TIPO_PAGO NUMBER, P_ID_FORMA_PAGO NUMBER, P_ID_ESTADO NUMBER) IS
    BEGIN
    INSERT INTO FIDE_SALARIOS_TB (ID_PERSONA, MONTO, TIPO_PAGO, ID_FORMA_PAGO, ID_ESTADO)
    VALUES (P_ID_PERSONA, P_MONTO, P_TIPO_PAGO, P_ID_FORMA_PAGO, P_ID_ESTADO);
    COMMIT;
    EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
    DBMS_OUTPUT.PUT_LINE('YA EXISTE UN SALARIO REGISTRADO PARA LA PERSONA ' || P_ID_PERSONA);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR SALARIO: ' || SQLERRM);
    END FIDE_SALARIOS_INSERTAR_SP;
    
    PROCEDURE FIDE_SALARIOS_ACTUALIZAR_SP(P_ID_PERSONA NUMBER, P_MONTO NUMBER, P_TIPO_PAGO NUMBER, P_ID_FORMA_PAGO NUMBER, P_ID_ESTADO NUMBER) IS
    BEGIN
    UPDATE FIDE_SALARIOS_TB
    SET MONTO = P_MONTO,
    TIPO_PAGO = P_TIPO_PAGO,
    ID_FORMA_PAGO = P_ID_FORMA_PAGO,
    ID_ESTADO = P_ID_ESTADO
    WHERE ID_PERSONA = P_ID_PERSONA;
    COMMIT;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL SALARIO DE LA PERSONA ' || P_ID_PERSONA);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR SALARIO: ' || SQLERRM);
    END FIDE_SALARIOS_ACTUALIZAR_SP;
    
    PROCEDURE FIDE_SALARIOS_ELIMINAR_SP(P_ID_PERSONA NUMBER) IS
    BEGIN
    UPDATE FIDE_SALARIOS_TB
    SET ID_ESTADO = 2
    WHERE ID_PERSONA = P_ID_PERSONA;
    COMMIT;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL SALARIO DE LA PERSONA ' || P_ID_PERSONA);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR SALARIO: ' || SQLERRM);
    END FIDE_SALARIOS_ELIMINAR_SP;
    
    PROCEDURE FIDE_PAQUETES_INSERTAR_SP(P_ID_PAQUETE NUMBER, P_ID_PERSONA NUMBER, P_ID_RESIDENCIA NUMBER, P_FECHA_INGRESO DATE, P_FECHA_SALIDA DATE, P_ID_ESTADO NUMBER) IS
    BEGIN
    INSERT INTO FIDE_PAQUETES_TB (ID_PAQUETE, ID_PERSONA, ID_RESIDENCIA, FECHA_INGRESO, FECHA_SALIDA, ID_ESTADO)
    VALUES (P_ID_PAQUETE, P_ID_PERSONA, P_ID_RESIDENCIA, P_FECHA_INGRESO, P_FECHA_SALIDA, P_ID_ESTADO);
    COMMIT;
    EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
    DBMS_OUTPUT.PUT_LINE('YA EXISTE UN PAQUETE CON EL ID ' || P_ID_PAQUETE);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR PAQUETE: ' || SQLERRM);
    END FIDE_PAQUETES_INSERTAR_SP;
    
    PROCEDURE FIDE_PAQUETES_ACTUALIZAR_SP(P_ID_PAQUETE NUMBER, P_ID_PERSONA NUMBER, P_ID_RESIDENCIA NUMBER, P_FECHA_INGRESO DATE, P_FECHA_SALIDA DATE, P_ID_ESTADO NUMBER) IS
    BEGIN
    UPDATE FIDE_PAQUETES_TB
    SET ID_PERSONA = P_ID_PERSONA,
    ID_RESIDENCIA = P_ID_RESIDENCIA,
    FECHA_INGRESO = P_FECHA_INGRESO,
    FECHA_SALIDA = P_FECHA_SALIDA,
    ID_ESTADO = P_ID_ESTADO
    WHERE ID_PAQUETE = P_ID_PAQUETE;
    COMMIT;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL PAQUETE CON ID ' || P_ID_PAQUETE);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR PAQUETE: ' || SQLERRM);
    END FIDE_PAQUETES_ACTUALIZAR_SP;
    
    PROCEDURE FIDE_PAQUETES_ELIMINAR_SP(P_ID_PAQUETE NUMBER) IS
    BEGIN
    UPDATE FIDE_PAQUETES_TB
    SET ID_ESTADO = 2
    WHERE ID_PAQUETE = P_ID_PAQUETE;
    COMMIT;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL PAQUETE CON ID ' || P_ID_PAQUETE);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR PAQUETE: ' || SQLERRM);
    END FIDE_PAQUETES_ELIMINAR_SP;
    
    PROCEDURE FIDE_TURNOS_INSERTAR_SP(P_ID_PERSONA NUMBER, P_ID_FECHAS NUMBER, P_ID_HORARIO NUMBER, P_ID_ESTADO NUMBER) IS
    BEGIN
    INSERT INTO FIDE_TURNOS_TB (ID_PERSONA, ID_FECHAS, ID_HORARIO, ID_ESTADO)
    VALUES (P_ID_PERSONA, P_ID_FECHAS, P_ID_HORARIO, P_ID_ESTADO);
    COMMIT;
    EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
    DBMS_OUTPUT.PUT_LINE('YA EXISTE UN TURNO PARA LA PERSONA ' || P_ID_PERSONA || ' EN ESA FECHA Y HORARIO');
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR TURNO: ' || SQLERRM);
    END FIDE_TURNOS_INSERTAR_SP;
    
    PROCEDURE FIDE_TURNOS_ACTUALIZAR_SP(P_ID_PERSONA NUMBER, P_ID_FECHAS NUMBER, P_ID_HORARIO NUMBER, P_ID_ESTADO NUMBER) IS
    BEGIN
    UPDATE FIDE_TURNOS_TB
    SET ID_ESTADO = P_ID_ESTADO
    WHERE ID_PERSONA = P_ID_PERSONA
    AND ID_FECHAS = P_ID_FECHAS
    AND ID_HORARIO = P_ID_HORARIO;
    COMMIT;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL TURNO DE LA PERSONA ' || P_ID_PERSONA);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR TURNO: ' || SQLERRM);
    END FIDE_TURNOS_ACTUALIZAR_SP;
    
    PROCEDURE FIDE_TURNOS_ELIMINAR_SP(P_ID_PERSONA NUMBER, P_ID_FECHAS NUMBER, P_ID_HORARIO NUMBER) IS
    BEGIN
    UPDATE FIDE_TURNOS_TB
    SET ID_ESTADO = 2
    WHERE ID_PERSONA = P_ID_PERSONA
    AND ID_FECHAS = P_ID_FECHAS
    AND ID_HORARIO = P_ID_HORARIO;
    COMMIT;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL TURNO DE LA PERSONA ' || P_ID_PERSONA);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR TURNO: ' || SQLERRM);
    END FIDE_TURNOS_ELIMINAR_SP;
    
    PROCEDURE FIDE_VISITAS_INSERTAR_SP(P_ID_VISITA NUMBER, P_ID_PERSONA NUMBER, P_FECHA_INGRESO DATE, P_FECHA_SALIDA DATE, P_ID_RESIDENCIA NUMBER, P_ID_ROL NUMBER, P_ID_ESTADO NUMBER) IS
    BEGIN
    INSERT INTO FIDE_VISITAS_TB (ID_VISITA, ID_PERSONA, FECHA_INGRESO, FECHA_SALIDA, ID_RESIDENCIA, ID_ROL, ID_ESTADO)
    VALUES (P_ID_VISITA, P_ID_PERSONA, P_FECHA_INGRESO, P_FECHA_SALIDA, P_ID_RESIDENCIA, P_ID_ROL, P_ID_ESTADO);
    COMMIT;
    EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
    DBMS_OUTPUT.PUT_LINE('YA EXISTE UNA VISITA CON EL ID ' || P_ID_VISITA);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR VISITA: ' || SQLERRM);
    END FIDE_VISITAS_INSERTAR_SP;
    
    PROCEDURE FIDE_VISITAS_ACTUALIZAR_SP(P_ID_VISITA NUMBER, P_ID_PERSONA NUMBER, P_FECHA_INGRESO DATE, P_FECHA_SALIDA DATE, P_ID_RESIDENCIA NUMBER, P_ID_ROL NUMBER, P_ID_ESTADO NUMBER) IS
    BEGIN
    UPDATE FIDE_VISITAS_TB
    SET ID_PERSONA = P_ID_PERSONA,
    FECHA_INGRESO = P_FECHA_INGRESO,
    FECHA_SALIDA = P_FECHA_SALIDA,
    ID_RESIDENCIA = P_ID_RESIDENCIA,
    ID_ROL = P_ID_ROL,
    ID_ESTADO = P_ID_ESTADO
    WHERE ID_VISITA = P_ID_VISITA;
    COMMIT;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO LA VISITA CON ID ' || P_ID_VISITA);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR VISITA: ' || SQLERRM);
    END FIDE_VISITAS_ACTUALIZAR_SP;
    
    PROCEDURE FIDE_VISITAS_ELIMINAR_SP(P_ID_VISITA NUMBER) IS
    BEGIN
    UPDATE FIDE_VISITAS_TB
    SET ID_ESTADO = 2
    WHERE ID_VISITA = P_ID_VISITA;
    COMMIT;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO LA VISITA CON ID ' || P_ID_VISITA);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR VISITA: ' || SQLERRM);
    END FIDE_VISITAS_ELIMINAR_SP;
    
    PROCEDURE FIDE_PERSONAS_SERVICIOS_INSERTAR_SP(P_ID_SERVICIO NUMBER, P_ID_PERSONA NUMBER, P_ID_ESTADO NUMBER) IS
    BEGIN
    INSERT INTO FIDE_PERSONAS_SERVICIOS_TB (ID_SERVICIO, ID_PERSONA, ID_ESTADO)
    VALUES (P_ID_SERVICIO, P_ID_PERSONA, P_ID_ESTADO);
    COMMIT;
    EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
    DBMS_OUTPUT.PUT_LINE('LA PERSONA ' || P_ID_PERSONA || ' YA ESTA ASIGNADA AL SERVICIO ' || P_ID_SERVICIO);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR ASIGNACION DE SERVICIO: ' || SQLERRM);
    END FIDE_PERSONAS_SERVICIOS_INSERTAR_SP;
    
    PROCEDURE FIDE_PERSONAS_SERVICIOS_ACTUALIZAR_SP(P_ID_SERVICIO NUMBER, P_ID_PERSONA NUMBER, P_ID_ESTADO NUMBER) IS
    BEGIN
    UPDATE FIDE_PERSONAS_SERVICIOS_TB
    SET ID_ESTADO = P_ID_ESTADO
    WHERE ID_SERVICIO = P_ID_SERVICIO
    AND ID_PERSONA = P_ID_PERSONA;
    COMMIT;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO LA ASIGNACION DE LA PERSONA ' || P_ID_PERSONA || ' AL SERVICIO ' || P_ID_SERVICIO);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR ASIGNACION DE SERVICIO: ' || SQLERRM);
    END FIDE_PERSONAS_SERVICIOS_ACTUALIZAR_SP;
    
    PROCEDURE FIDE_PERSONAS_SERVICIOS_ELIMINAR_SP(P_ID_SERVICIO NUMBER, P_ID_PERSONA NUMBER) IS
    BEGIN
    UPDATE FIDE_PERSONAS_SERVICIOS_TB
    SET ID_ESTADO = 2
    WHERE ID_SERVICIO = P_ID_SERVICIO
    AND ID_PERSONA = P_ID_PERSONA;
    COMMIT;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO LA ASIGNACION DE LA PERSONA ' || P_ID_PERSONA || ' AL SERVICIO ' || P_ID_SERVICIO);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR ASIGNACION DE SERVICIO: ' || SQLERRM);
    END FIDE_PERSONAS_SERVICIOS_ELIMINAR_SP;
    
    PROCEDURE FIDE_RESUMENES_TURNOS_INSERTAR_SP(P_ID_RESUMEN NUMBER, P_DESCRIPCION VARCHAR2, P_ID_FECHAS NUMBER, P_ID_HORARIO NUMBER, P_ID_CONSULTA NUMBER, P_ID_REPORTE NUMBER, P_ID_ESTADO NUMBER) IS
    BEGIN
    INSERT INTO FIDE_RESUMENES_TURNOS_TB (ID_RESUMEN, DESCRIPCION, ID_FECHAS, ID_HORARIO, ID_CONSULTA, ID_REPORTE, ID_ESTADO)
    VALUES (P_ID_RESUMEN, P_DESCRIPCION, P_ID_FECHAS, P_ID_HORARIO, P_ID_CONSULTA, P_ID_REPORTE, P_ID_ESTADO);
    COMMIT;
    EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
    DBMS_OUTPUT.PUT_LINE('YA EXISTE UN RESUMEN DE TURNO CON EL ID ' || P_ID_RESUMEN);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR RESUMEN DE TURNO: ' || SQLERRM);
    END FIDE_RESUMENES_TURNOS_INSERTAR_SP;
    
    PROCEDURE FIDE_RESUMENES_TURNOS_ACTUALIZAR_SP(P_ID_RESUMEN NUMBER, P_DESCRIPCION VARCHAR2, P_ID_FECHAS NUMBER, P_ID_HORARIO NUMBER, P_ID_CONSULTA NUMBER, P_ID_REPORTE NUMBER, P_ID_ESTADO NUMBER) IS
    BEGIN
    UPDATE FIDE_RESUMENES_TURNOS_TB
    SET DESCRIPCION = P_DESCRIPCION,
    ID_FECHAS = P_ID_FECHAS,
    ID_HORARIO = P_ID_HORARIO,
    ID_CONSULTA = P_ID_CONSULTA,
    ID_REPORTE = P_ID_REPORTE,
    ID_ESTADO = P_ID_ESTADO
    WHERE ID_RESUMEN = P_ID_RESUMEN;
    COMMIT;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL RESUMEN DE TURNO CON ID ' || P_ID_RESUMEN);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR RESUMEN DE TURNO: ' || SQLERRM);
    END FIDE_RESUMENES_TURNOS_ACTUALIZAR_SP;
    
    PROCEDURE FIDE_RESUMENES_TURNOS_ELIMINAR_SP(P_ID_RESUMEN NUMBER) IS
    BEGIN
    UPDATE FIDE_RESUMENES_TURNOS_TB
    SET ID_ESTADO = 2
    WHERE ID_RESUMEN = P_ID_RESUMEN;
    COMMIT;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL RESUMEN DE TURNO CON ID ' || P_ID_RESUMEN);
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR RESUMEN DE TURNO: ' || SQLERRM);
    END FIDE_RESUMENES_TURNOS_ELIMINAR_SP;

END FIDE_CONDOMINIO_PKG;
/


