
-- PROYECTO CONDOMINIO LAS ARALIAS


CREATE TABLE FIDE_ESTADOS_TB (
    ID_ESTADO     NUMBER CONSTRAINT ESTADOS_ID_ESTADO_PK PRIMARY KEY,
    NOMBRE_ESTADO VARCHAR2(30)
);

CREATE TABLE FIDE_ROLES_TB (
    ID_ROL    NUMBER CONSTRAINT ROLES_ID_ROL_PK PRIMARY KEY,
    ROL       VARCHAR2(50),
    ID_ESTADO NUMBER,
    CONSTRAINT ROLES_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADOS_TB (ID_ESTADO)
);

CREATE TABLE FIDE_TIPOS_PAGO_TB (
    ID_TIPO_PAGO NUMBER CONSTRAINT TIPOS_PAGO_ID_TIPO_PAGO_PK PRIMARY KEY,
    TIPO         VARCHAR2(50),
    ID_ESTADO    NUMBER,
    CONSTRAINT TIPOS_PAGO_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADOS_TB (ID_ESTADO)
);

CREATE TABLE FIDE_FORMAS_PAGOS_TB (
    ID_FORMA_PAGO NUMBER CONSTRAINT FORMAS_PAGOS_ID_FORMA_PAGO_PK PRIMARY KEY,
    FORMA         VARCHAR2(50),
    ID_ESTADO     NUMBER,
    CONSTRAINT FORMAS_PAGOS_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADOS_TB (ID_ESTADO)
);

CREATE TABLE FIDE_HORARIOS_TURNOS_TB (
    ID_HORARIO    NUMBER CONSTRAINT HORARIOS_TURNOS_ID_HORARIO_PK PRIMARY KEY,
    HORARIO_TURNO VARCHAR2(60),
    ID_ESTADO     NUMBER,
    CONSTRAINT HORARIOS_TURNOS_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADOS_TB (ID_ESTADO)
);

CREATE TABLE FIDE_FECHAS_TURNOS_TB (
    ID_FECHAS    NUMBER CONSTRAINT FECHAS_TURNOS_ID_FECHAS_PK PRIMARY KEY,
    FECHAS_TURNO DATE,
    ID_ESTADO    NUMBER,
    CONSTRAINT FECHAS_TURNOS_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADOS_TB (ID_ESTADO)
);

CREATE TABLE FIDE_TIPOS_ESPACIOS_TB (
    ID_TIPO_ESPACIO NUMBER CONSTRAINT TIPOS_ESPACIOS_ID_TIPO_ESPACIO_PK PRIMARY KEY,
    NOMBRE_ESPACIO  VARCHAR2(60),
    DESCR_ESPACIO   VARCHAR2(200),
    ID_ESTADO       NUMBER,
    CONSTRAINT TIPOS_ESPACIOS_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADOS_TB (ID_ESTADO)
);

CREATE TABLE FIDE_TIPOS_EVENTOS_TB (
    ID_TIPO_EVENTO NUMBER CONSTRAINT TIPOS_EVENTOS_ID_TIPO_EVENTO_PK PRIMARY KEY,
    TIPO_EVENTO    VARCHAR2(60),
    ID_ESTADO      NUMBER,
    CONSTRAINT TIPOS_EVENTOS_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADOS_TB (ID_ESTADO)
);

CREATE TABLE FIDE_TIPOS_SERVICIOS_TB (
    ID_TIPO_SERVICIO NUMBER CONSTRAINT TIPOS_SERVICIOS_ID_TIPO_SERVICIO_PK PRIMARY KEY,
    TIPO_SERVICIO    VARCHAR2(60),
    ID_ESTADO        NUMBER,
    CONSTRAINT TIPOS_SERVICIOS_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADOS_TB (ID_ESTADO)
);

CREATE TABLE FIDE_PERSONAS_TB (
    ID_PERSONA       NUMBER CONSTRAINT PERSONAS_ID_PERSONA_PK PRIMARY KEY,
    NOMBRE           VARCHAR2(60),
    APELLIDO_PATERNO VARCHAR2(60),
    APELLIDO_MATERNO VARCHAR2(60),
    FECHA_REGISTRO   DATE,
    ID_ROL           NUMBER,
    ID_ESTADO        NUMBER,
    CONSTRAINT PERSONAS_ID_ROL_FK FOREIGN KEY (ID_ROL)
        REFERENCES FIDE_ROLES_TB (ID_ROL),
    CONSTRAINT PERSONAS_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADOS_TB (ID_ESTADO)
);

CREATE TABLE FIDE_TELEFONOS_TB (
    ID_TELEFONO NUMBER CONSTRAINT TELEFONOS_ID_TELEFONO_PK PRIMARY KEY,
    ID_PERSONA  NUMBER,
    TELEFONO    VARCHAR2(20),
    ID_ESTADO   NUMBER,
    CONSTRAINT TELEFONOS_ID_PERSONA_FK FOREIGN KEY (ID_PERSONA)
        REFERENCES FIDE_PERSONAS_TB (ID_PERSONA),
    CONSTRAINT TELEFONOS_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADOS_TB (ID_ESTADO)
);

CREATE TABLE FIDE_CORREOS_TB (
    ID_CORREO  NUMBER CONSTRAINT CORREOS_ID_CORREO_PK PRIMARY KEY,
    ID_PERSONA NUMBER,
    CORREO     VARCHAR2(120),
    ID_ESTADO  NUMBER,
    CONSTRAINT CORREOS_ID_PERSONA_FK FOREIGN KEY (ID_PERSONA)
        REFERENCES FIDE_PERSONAS_TB (ID_PERSONA),
    CONSTRAINT CORREOS_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADOS_TB (ID_ESTADO)
);

CREATE TABLE FIDE_RESIDENCIAS_TB (
    ID_RESIDENCIA       NUMBER CONSTRAINT RESIDENCIAS_ID_RESIDENCIA_PK PRIMARY KEY,
    MONTO_ALQUILER      NUMBER(12,2),
    MONTO_MANTENIMIENTO NUMBER(12,2),
    ID_TIPO_PAGO        NUMBER,
    ID_ESTADO           NUMBER,
    CONSTRAINT RESIDENCIAS_ID_TIPO_PAGO_FK FOREIGN KEY (ID_TIPO_PAGO)
        REFERENCES FIDE_TIPOS_PAGO_TB (ID_TIPO_PAGO),
    CONSTRAINT RESIDENCIAS_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADOS_TB (ID_ESTADO),
    CONSTRAINT RESIDENCIAS_MONTOS_CK CHECK (
        MONTO_ALQUILER >= 0 AND MONTO_MANTENIMIENTO >= 0
    )
);

CREATE TABLE FIDE_RESIDENTES_TB (
    ID_PERSONA    NUMBER,
    ID_RESIDENCIA NUMBER,
    ID_ESTADO     NUMBER,
    CONSTRAINT RESIDENTES_ID_PERSONA_ID_RESIDENCIA_PK PRIMARY KEY (ID_PERSONA, ID_RESIDENCIA),
    CONSTRAINT RESIDENTES_ID_PERSONA_FK FOREIGN KEY (ID_PERSONA)
        REFERENCES FIDE_PERSONAS_TB (ID_PERSONA),
    CONSTRAINT RESIDENTES_ID_RESIDENCIA_FK FOREIGN KEY (ID_RESIDENCIA)
        REFERENCES FIDE_RESIDENCIAS_TB (ID_RESIDENCIA),
    CONSTRAINT RESIDENTES_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADOS_TB (ID_ESTADO)
);

CREATE TABLE FIDE_EVENTOS_TB (
    ID_EVENTO       NUMBER CONSTRAINT EVENTOS_ID_EVENTO_PK PRIMARY KEY,
    DESCR_EVENTO    VARCHAR2(200),
    FECHA_EVENTO    DATE,
    ID_TIPO_EVENTO  NUMBER,
    ID_TIPO_ESPACIO NUMBER,
    ID_ESTADO       NUMBER,
    CONSTRAINT EVENTOS_ID_TIPO_EVENTO_FK FOREIGN KEY (ID_TIPO_EVENTO)
        REFERENCES FIDE_TIPOS_EVENTOS_TB (ID_TIPO_EVENTO),
    CONSTRAINT EVENTOS_ID_TIPO_ESPACIO_FK FOREIGN KEY (ID_TIPO_ESPACIO)
        REFERENCES FIDE_TIPOS_ESPACIOS_TB (ID_TIPO_ESPACIO),
    CONSTRAINT EVENTOS_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADOS_TB (ID_ESTADO)
);

CREATE TABLE FIDE_VEHICULOS_TB (
    PLACA           VARCHAR2(15) CONSTRAINT VEHICULOS_PLACA_PK PRIMARY KEY,
    DESCRIPCION     VARCHAR2(120),
    ID_TIPO_ESPACIO NUMBER,
    ID_PERSONA      NUMBER,
    ID_ESTADO       NUMBER,
    CONSTRAINT VEHICULOS_ID_TIPO_ESPACIO_FK FOREIGN KEY (ID_TIPO_ESPACIO)
        REFERENCES FIDE_TIPOS_ESPACIOS_TB (ID_TIPO_ESPACIO),
    CONSTRAINT VEHICULOS_ID_PERSONA_FK FOREIGN KEY (ID_PERSONA)
        REFERENCES FIDE_PERSONAS_TB (ID_PERSONA),
    CONSTRAINT VEHICULOS_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADOS_TB (ID_ESTADO)
);

CREATE TABLE FIDE_SERVICIOS_TB (
    ID_SERVICIO      NUMBER CONSTRAINT SERVICIOS_ID_SERVICIO_PK PRIMARY KEY,
    DESCR_SERVICIO   VARCHAR2(200),
    FECHA_SALIDA     DATE,
    ID_TIPO_SERVICIO NUMBER,
    ID_TIPO_EVENTO   NUMBER,
    ID_ESTADO        NUMBER,
    CONSTRAINT SERVICIOS_ID_TIPO_SERVICIO_FK FOREIGN KEY (ID_TIPO_SERVICIO)
        REFERENCES FIDE_TIPOS_SERVICIOS_TB (ID_TIPO_SERVICIO),
    CONSTRAINT SERVICIOS_ID_TIPO_EVENTO_FK FOREIGN KEY (ID_TIPO_EVENTO)
        REFERENCES FIDE_TIPOS_EVENTOS_TB (ID_TIPO_EVENTO),
    CONSTRAINT SERVICIOS_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADOS_TB (ID_ESTADO)
);

CREATE TABLE FIDE_FACTURAS_TB (
    ID_FACTURA    NUMBER CONSTRAINT FACTURAS_ID_FACTURA_PK PRIMARY KEY,
    FECHA_FACTURA DATE,
    DESCR_FACTURA VARCHAR2(200),
    ID_TIPO_PAGO  NUMBER,
    ID_FORMA_PAGO NUMBER,
    ID_PERSONA    NUMBER,
    ID_ESTADO     NUMBER,
    CONSTRAINT FACTURAS_ID_TIPO_PAGO_FK FOREIGN KEY (ID_TIPO_PAGO)
        REFERENCES FIDE_TIPOS_PAGO_TB (ID_TIPO_PAGO),
    CONSTRAINT FACTURAS_ID_FORMA_PAGO_FK FOREIGN KEY (ID_FORMA_PAGO)
        REFERENCES FIDE_FORMAS_PAGOS_TB (ID_FORMA_PAGO),
    CONSTRAINT FACTURAS_ID_PERSONA_FK FOREIGN KEY (ID_PERSONA)
        REFERENCES FIDE_PERSONAS_TB (ID_PERSONA),
    CONSTRAINT FACTURAS_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADOS_TB (ID_ESTADO)
);


CREATE TABLE FIDE_CONSULTAS_TB (
    ID_CONSULTA    NUMBER CONSTRAINT CONSULTAS_ID_CONSULTA_PK PRIMARY KEY,
    CONSULTA       VARCHAR2(200),
    FECHA_CONSULTA DATE,
    ID_PERSONA     NUMBER,
    ID_ESTADO      NUMBER,
    CONSTRAINT CONSULTAS_ID_PERSONA_FK FOREIGN KEY (ID_PERSONA)
        REFERENCES FIDE_PERSONAS_TB (ID_PERSONA),
    CONSTRAINT CONSULTAS_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADOS_TB (ID_ESTADO)
);

CREATE TABLE FIDE_REPORTES_TB (
    ID_REPORTE    NUMBER CONSTRAINT REPORTES_ID_REPORTE_PK PRIMARY KEY,
    REPORTE       VARCHAR2(200),
    FECHA_REPORTE DATE,
    ID_PERSONA    NUMBER,
    ID_ESTADO     NUMBER,
    CONSTRAINT REPORTES_ID_PERSONA_FK FOREIGN KEY (ID_PERSONA)
        REFERENCES FIDE_PERSONAS_TB (ID_PERSONA),
    CONSTRAINT REPORTES_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADOS_TB (ID_ESTADO)
);

CREATE TABLE FIDE_SALARIOS_TB (
    ID_PERSONA    NUMBER CONSTRAINT SALARIOS_ID_PERSONA_PK PRIMARY KEY,
    MONTO         NUMBER(12,2),
    TIPO_PAGO     NUMBER,
    ID_FORMA_PAGO NUMBER,
    ID_ESTADO     NUMBER,
    CONSTRAINT SALARIOS_ID_PERSONA_FK FOREIGN KEY (ID_PERSONA)
        REFERENCES FIDE_PERSONAS_TB (ID_PERSONA),
    CONSTRAINT SALARIOS_TIPO_PAGO_FK FOREIGN KEY (TIPO_PAGO)
        REFERENCES FIDE_TIPOS_PAGO_TB (ID_TIPO_PAGO),
    CONSTRAINT SALARIOS_ID_FORMA_PAGO_FK FOREIGN KEY (ID_FORMA_PAGO)
        REFERENCES FIDE_FORMAS_PAGOS_TB (ID_FORMA_PAGO),
    CONSTRAINT SALARIOS_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADOS_TB (ID_ESTADO),
    CONSTRAINT SALARIOS_MONTO_CK CHECK (MONTO >= 0)
);

CREATE TABLE FIDE_PAQUETES_TB (
    ID_PAQUETE    NUMBER CONSTRAINT PAQUETES_ID_PAQUETE_PK PRIMARY KEY,
    ID_PERSONA    NUMBER,
    ID_RESIDENCIA NUMBER,
    FECHA_INGRESO DATE,
    FECHA_SALIDA  DATE,
    ID_ESTADO     NUMBER,
    CONSTRAINT PAQUETES_ID_PERSONA_FK FOREIGN KEY (ID_PERSONA)
        REFERENCES FIDE_PERSONAS_TB (ID_PERSONA),
    CONSTRAINT PAQUETES_ID_RESIDENCIA_FK FOREIGN KEY (ID_RESIDENCIA)
        REFERENCES FIDE_RESIDENCIAS_TB (ID_RESIDENCIA),
    CONSTRAINT PAQUETES_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADOS_TB (ID_ESTADO)
);

CREATE TABLE FIDE_TURNOS_TB (
    ID_PERSONA NUMBER,
    ID_FECHAS  NUMBER,
    ID_HORARIO NUMBER,
    ID_ESTADO  NUMBER,
    CONSTRAINT TURNOS_ID_PERSONA_ID_FECHAS_ID_HORARIO_PK PRIMARY KEY (ID_PERSONA, ID_FECHAS, ID_HORARIO),
    CONSTRAINT TURNOS_ID_PERSONA_FK FOREIGN KEY (ID_PERSONA)
        REFERENCES FIDE_PERSONAS_TB (ID_PERSONA),
    CONSTRAINT TURNOS_ID_FECHAS_FK FOREIGN KEY (ID_FECHAS)
        REFERENCES FIDE_FECHAS_TURNOS_TB (ID_FECHAS),
    CONSTRAINT TURNOS_ID_HORARIO_FK FOREIGN KEY (ID_HORARIO)
        REFERENCES FIDE_HORARIOS_TURNOS_TB (ID_HORARIO),
    CONSTRAINT TURNOS_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADOS_TB (ID_ESTADO)
);

CREATE TABLE FIDE_VISITAS_TB (
    ID_VISITA     NUMBER CONSTRAINT VISITAS_ID_VISITA_PK PRIMARY KEY,
    ID_PERSONA    NUMBER,
    FECHA_INGRESO DATE,
    FECHA_SALIDA  DATE,
    ID_RESIDENCIA NUMBER,
    ID_ROL        NUMBER,
    ID_ESTADO     NUMBER,
    CONSTRAINT VISITAS_ID_PERSONA_FK FOREIGN KEY (ID_PERSONA)
        REFERENCES FIDE_PERSONAS_TB (ID_PERSONA),
    CONSTRAINT VISITAS_ID_RESIDENCIA_FK FOREIGN KEY (ID_RESIDENCIA)
        REFERENCES FIDE_RESIDENCIAS_TB (ID_RESIDENCIA),
    CONSTRAINT VISITAS_ID_ROL_FK FOREIGN KEY (ID_ROL)
        REFERENCES FIDE_ROLES_TB (ID_ROL),
    CONSTRAINT VISITAS_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADOS_TB (ID_ESTADO)
);

CREATE TABLE FIDE_PERSONAS_SERVICIOS_TB (
    ID_SERVICIO NUMBER,
    ID_PERSONA  NUMBER,
    ID_ESTADO   NUMBER,
    CONSTRAINT PERSONAS_SERVICIOS_ID_SERVICIO_ID_PERSONA_PK PRIMARY KEY (ID_SERVICIO, ID_PERSONA),
    CONSTRAINT PERSONAS_SERVICIOS_ID_SERVICIO_FK FOREIGN KEY (ID_SERVICIO)
        REFERENCES FIDE_SERVICIOS_TB (ID_SERVICIO),
    CONSTRAINT PERSONAS_SERVICIOS_ID_PERSONA_FK FOREIGN KEY (ID_PERSONA)
        REFERENCES FIDE_PERSONAS_TB (ID_PERSONA),
    CONSTRAINT PERSONAS_SERVICIOS_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADOS_TB (ID_ESTADO)
);

CREATE TABLE FIDE_RESUMENES_TURNOS_TB (
    ID_RESUMEN  NUMBER CONSTRAINT RESUMENES_TURNOS_ID_RESUMEN_PK PRIMARY KEY,
    DESCRIPCION VARCHAR2(200),
    ID_FECHAS   NUMBER,
    ID_HORARIO  NUMBER,
    ID_CONSULTA NUMBER,
    ID_REPORTE  NUMBER,
    ID_ESTADO   NUMBER,
    CONSTRAINT RESUMENES_TURNOS_ID_FECHAS_FK FOREIGN KEY (ID_FECHAS)
        REFERENCES FIDE_FECHAS_TURNOS_TB (ID_FECHAS),
    CONSTRAINT RESUMENES_TURNOS_ID_HORARIO_FK FOREIGN KEY (ID_HORARIO)
        REFERENCES FIDE_HORARIOS_TURNOS_TB (ID_HORARIO),
    CONSTRAINT RESUMENES_TURNOS_ID_CONSULTA_FK FOREIGN KEY (ID_CONSULTA)
        REFERENCES FIDE_CONSULTAS_TB (ID_CONSULTA),
    CONSTRAINT RESUMENES_TURNOS_ID_REPORTE_FK FOREIGN KEY (ID_REPORTE)
        REFERENCES FIDE_REPORTES_TB (ID_REPORTE),
    CONSTRAINT RESUMENES_TURNOS_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADOS_TB (ID_ESTADO)
);


COMMIT;