CREATE OR REPLACE VIEW FIDE_RESIDENTES_DETALLE_V AS
SELECT
    P.ID_PERSONA AS "ID Persona",
    P.NOMBRE || ' ' || P.APELLIDO_PATERNO || ' ' || P.APELLIDO_MATERNO AS "Residente",
    R.ID_RESIDENCIA AS "ID Residencia",
    R.MONTO_ALQUILER AS "Monto Alquiler",
    R.MONTO_MANTENIMIENTO AS "Monto Mantenimiento",
    TP.TIPO AS "Tipo de Pago",
    E.NOMBRE_ESTADO AS "Estado Residencia"
FROM FIDE_RESIDENTES_TB RS
JOIN FIDE_PERSONAS_TB P ON RS.ID_PERSONA = P.ID_PERSONA
JOIN FIDE_RESIDENCIAS_TB R ON RS.ID_RESIDENCIA = R.ID_RESIDENCIA
JOIN FIDE_TIPOS_PAGO_TB TP ON R.ID_TIPO_PAGO = TP.ID_TIPO_PAGO
JOIN FIDE_ESTADOS_TB E ON R.ID_ESTADO = E.ID_ESTADO
ORDER BY R.ID_RESIDENCIA, P.APELLIDO_PATERNO;

SELECT * FROM FIDE_RESIDENTES_DETALLE_V;


CREATE OR REPLACE VIEW FIDE_FACTURAS_DETALLE_V AS
SELECT
    F.ID_FACTURA AS "N Factura",
    P.NOMBRE || ' ' || P.APELLIDO_PATERNO || ' ' || P.APELLIDO_MATERNO AS "Persona",
    F.FECHA_FACTURA AS "Fecha Factura",
    F.DESCR_FACTURA AS "Descripcion",
    TP.TIPO AS "Tipo de Pago",
    FP.FORMA AS "Forma de Pago",
    E.NOMBRE_ESTADO AS "Estado Factura"
FROM FIDE_FACTURAS_TB F
JOIN FIDE_PERSONAS_TB P ON F.ID_PERSONA = P.ID_PERSONA
JOIN FIDE_TIPOS_PAGO_TB TP ON F.ID_TIPO_PAGO = TP.ID_TIPO_PAGO
JOIN FIDE_FORMAS_PAGOS_TB FP ON F.ID_FORMA_PAGO = FP.ID_FORMA_PAGO
JOIN FIDE_ESTADOS_TB E ON F.ID_ESTADO = E.ID_ESTADO
ORDER BY F.FECHA_FACTURA DESC;

SELECT * FROM FIDE_FACTURAS_DETALLE_V;


CREATE OR REPLACE VIEW FIDE_VISITAS_DETALLE_V AS
SELECT
    VI.ID_PERSONA AS "ID Visitante",
    PV.NOMBRE || ' ' || PV.APELLIDO_PATERNO || ' ' || PV.APELLIDO_MATERNO AS "Visitante",
    TO_CHAR(VI.FECHA_INGRESO, 'DD/MM/YYYY HH24:MI') AS "Fecha Ingreso",
    TO_CHAR(VI.FECHA_SALIDA, 'DD/MM/YYYY HH24:MI') AS "Fecha Salida",
    VI.ID_RESIDENCIA AS "Residencia Visitada",
    R.ROL AS "Rol Visitante",
    E.NOMBRE_ESTADO AS "Estado Visita"
FROM FIDE_VISITAS_TB VI
JOIN FIDE_PERSONAS_TB PV ON VI.ID_PERSONA = PV.ID_PERSONA
JOIN FIDE_ROLES_TB R ON VI.ID_ROL = R.ID_ROL
JOIN FIDE_ESTADOS_TB E ON VI.ID_ESTADO = E.ID_ESTADO
ORDER BY VI.FECHA_INGRESO DESC;

SELECT * FROM FIDE_VISITAS_DETALLE_V;


CREATE OR REPLACE VIEW FIDE_TURNOS_GUARDIAS_V AS
SELECT
    P.ID_PERSONA AS "ID Guardia",
    P.NOMBRE || ' ' || P.APELLIDO_PATERNO || ' ' || P.APELLIDO_MATERNO AS "Guardia",
    FT.FECHAS_TURNO AS "Fecha Turno",
    HT.HORARIO_TURNO AS "Horario",
    E.NOMBRE_ESTADO AS "Estado Turno"
FROM FIDE_TURNOS_TB T
JOIN FIDE_PERSONAS_TB P ON T.ID_PERSONA = P.ID_PERSONA
JOIN FIDE_FECHAS_TURNOS_TB FT ON T.ID_FECHAS = FT.ID_FECHAS
JOIN FIDE_HORARIOS_TURNOS_TB HT ON T.ID_HORARIO = HT.ID_HORARIO
JOIN FIDE_ESTADOS_TB E ON T.ID_ESTADO = E.ID_ESTADO
ORDER BY FT.FECHAS_TURNO, HT.ID_HORARIO;

SELECT * FROM FIDE_TURNOS_GUARDIAS_V;


CREATE OR REPLACE VIEW FIDE_EVENTOS_DETALLE_V AS
SELECT
    EV.ID_EVENTO AS "ID Evento",
    EV.DESCR_EVENTO AS "Descripcion",
    TO_CHAR(EV.FECHA_EVENTO, 'DD/MM/YYYY HH24:MI') AS "Fecha Evento",
    TE.TIPO_EVENTO AS "Tipo de Evento",
    ES.NOMBRE_ESPACIO AS "Espacio Asignado",
    E.NOMBRE_ESTADO AS "Estado Evento"
FROM FIDE_EVENTOS_TB EV
JOIN FIDE_TIPOS_EVENTOS_TB TE ON EV.ID_TIPO_EVENTO = TE.ID_TIPO_EVENTO
JOIN FIDE_TIPOS_ESPACIOS_TB ES ON EV.ID_TIPO_ESPACIO = ES.ID_TIPO_ESPACIO
JOIN FIDE_ESTADOS_TB E ON EV.ID_ESTADO = E.ID_ESTADO
ORDER BY EV.FECHA_EVENTO DESC;

SELECT * FROM FIDE_EVENTOS_DETALLE_V;


CREATE OR REPLACE VIEW FIDE_VEHICULOS_PROPIETARIOS_V AS
SELECT
    VH.PLACA AS "Placa",
    VH.DESCRIPCION AS "Descripcion Vehiculo",
    P.NOMBRE || ' ' || P.APELLIDO_PATERNO || ' ' || P.APELLIDO_MATERNO AS "Propietario",
    TE.NOMBRE_ESPACIO AS "Tipo Espacio Parqueo",
    E.NOMBRE_ESTADO AS "Estado Vehiculo"
FROM FIDE_VEHICULOS_TB VH
JOIN FIDE_PERSONAS_TB P ON VH.ID_PERSONA = P.ID_PERSONA
JOIN FIDE_TIPOS_ESPACIOS_TB TE ON VH.ID_TIPO_ESPACIO = TE.ID_TIPO_ESPACIO
JOIN FIDE_ESTADOS_TB E ON VH.ID_ESTADO = E.ID_ESTADO
ORDER BY P.APELLIDO_PATERNO;

SELECT * FROM FIDE_VEHICULOS_PROPIETARIOS_V;


CREATE OR REPLACE VIEW FIDE_RESUMENES_TURNOS_V AS
SELECT
    RT.ID_RESUMEN AS "ID Resumen",
    RT.DESCRIPCION AS "Descripcion Turno",
    FT.FECHAS_TURNO AS "Fecha Turno",
    HT.HORARIO_TURNO AS "Horario",
    C.CONSULTA AS "Consulta Asociada",
    R.REPORTE AS "Reporte Asociado",
    E.NOMBRE_ESTADO AS "Estado Resumen"
FROM FIDE_RESUMENES_TURNOS_TB RT
JOIN FIDE_FECHAS_TURNOS_TB FT ON RT.ID_FECHAS = FT.ID_FECHAS
JOIN FIDE_HORARIOS_TURNOS_TB HT ON RT.ID_HORARIO = HT.ID_HORARIO
JOIN FIDE_CONSULTAS_TB C ON RT.ID_CONSULTA = C.ID_CONSULTA
JOIN FIDE_REPORTES_TB R ON RT.ID_REPORTE = R.ID_REPORTE
JOIN FIDE_ESTADOS_TB E ON RT.ID_ESTADO = E.ID_ESTADO
ORDER BY FT.FECHAS_TURNO DESC;

SELECT * FROM FIDE_RESUMENES_TURNOS_V;


CREATE OR REPLACE VIEW FIDE_SERVICIOS_ASIGNADOS_V AS
SELECT
    S.ID_SERVICIO AS "ID Servicio",
    S.DESCR_SERVICIO AS "Descripcion Servicio",
    S.FECHA_SALIDA AS "Fecha Programada",
    TS.TIPO_SERVICIO AS "Tipo Servicio",
    TE.TIPO_EVENTO AS "Tipo Evento",
    P.NOMBRE || ' ' || P.APELLIDO_PATERNO || ' ' || P.APELLIDO_MATERNO AS "Trabajador Asignado",
    E.NOMBRE_ESTADO AS "Estado Servicio"
FROM FIDE_SERVICIOS_TB S
JOIN FIDE_PERSONAS_SERVICIOS_TB PS ON S.ID_SERVICIO = PS.ID_SERVICIO
JOIN FIDE_PERSONAS_TB P ON PS.ID_PERSONA = P.ID_PERSONA
JOIN FIDE_TIPOS_SERVICIOS_TB TS ON S.ID_TIPO_SERVICIO = TS.ID_TIPO_SERVICIO
JOIN FIDE_TIPOS_EVENTOS_TB TE ON S.ID_TIPO_EVENTO = TE.ID_TIPO_EVENTO
JOIN FIDE_ESTADOS_TB E ON S.ID_ESTADO = E.ID_ESTADO
ORDER BY S.FECHA_SALIDA;

SELECT * FROM FIDE_SERVICIOS_ASIGNADOS_V;

CREATE OR REPLACE VIEW FIDE_PAQUETES_DETALLE_V AS
SELECT
    PA.ID_PAQUETE AS "ID Paquete",
    P.NOMBRE || ' ' || P.APELLIDO_PATERNO || ' ' || P.APELLIDO_MATERNO AS "Recibido Por",
    PA.ID_RESIDENCIA AS "Residencia",
    TO_CHAR(PA.FECHA_INGRESO, 'DD/MM/YYYY HH24:MI') AS "Fecha Ingreso",
    TO_CHAR(PA.FECHA_SALIDA, 'DD/MM/YYYY HH24:MI') AS "Fecha Entrega",
    E.NOMBRE_ESTADO AS "Estado Paquete"
FROM FIDE_PAQUETES_TB PA
JOIN FIDE_PERSONAS_TB P ON PA.ID_PERSONA = P.ID_PERSONA
JOIN FIDE_ESTADOS_TB E ON PA.ID_ESTADO = E.ID_ESTADO
ORDER BY PA.FECHA_INGRESO DESC;

CREATE MATERIALIZED VIEW FIDE_RESUMEN_FACTURACION_VM AS
SELECT
    P.ID_PERSONA AS ID_PERSONA,
    P.NOMBRE || ' ' || P.APELLIDO_PATERNO || ' ' || P.APELLIDO_MATERNO AS PERSONA,
    COUNT(F.ID_FACTURA) AS TOTAL_FACTURAS,
    COUNT(CASE WHEN TP.TIPO = 'MENSUAL' THEN 1 END) AS FACTURAS_MENSUAL,
    COUNT(CASE WHEN TP.TIPO = 'UNICO' THEN 1 END) AS FACTURAS_UNICO,
    FP.FORMA AS FORMA_PAGO_FRECUENTE
FROM FIDE_FACTURAS_TB F
JOIN FIDE_PERSONAS_TB P ON F.ID_PERSONA = P.ID_PERSONA
JOIN FIDE_TIPOS_PAGO_TB TP ON F.ID_TIPO_PAGO = TP.ID_TIPO_PAGO
JOIN FIDE_FORMAS_PAGOS_TB FP ON F.ID_FORMA_PAGO = FP.ID_FORMA_PAGO
GROUP BY
    P.ID_PERSONA,
    P.NOMBRE,
    P.APELLIDO_PATERNO,
    P.APELLIDO_MATERNO,
    FP.FORMA;

SELECT * FROM FIDE_RESUMEN_FACTURACION_VM;


CREATE MATERIALIZED VIEW FIDE_RESUMEN_SERVICIOS_VM AS
SELECT
    P.ID_PERSONA AS ID_PERSONA,
    P.NOMBRE || ' ' || P.APELLIDO_PATERNO || ' ' || P.APELLIDO_MATERNO AS TRABAJADOR,
    TS.TIPO_SERVICIO AS TIPO_SERVICIO,
    COUNT(S.ID_SERVICIO) AS TOTAL_SERVICIOS,
    MIN(S.FECHA_SALIDA) AS PRIMER_SERVICIO,
    MAX(S.FECHA_SALIDA) AS ULTIMO_SERVICIO
FROM FIDE_PERSONAS_SERVICIOS_TB PS
JOIN FIDE_PERSONAS_TB P ON PS.ID_PERSONA = P.ID_PERSONA
JOIN FIDE_SERVICIOS_TB S ON PS.ID_SERVICIO = S.ID_SERVICIO
JOIN FIDE_TIPOS_SERVICIOS_TB TS ON S.ID_TIPO_SERVICIO = TS.ID_TIPO_SERVICIO
GROUP BY
    P.ID_PERSONA,
    P.NOMBRE,
    P.APELLIDO_PATERNO,
    P.APELLIDO_MATERNO,
    TS.TIPO_SERVICIO
ORDER BY TOTAL_SERVICIOS DESC;

SELECT * FROM FIDE_RESUMEN_SERVICIOS_VM;