PROCEDURE FIDE_ESTADOS_ACTUALIZAR_SP(P_ID_ESTADO NUMBER, P_NOMBRE_ESTADO VARCHAR2) IS
BEGIN
UPDATE FIDE_ESTADOS_TB
SET NOMBRE_ESTADO = P_NOMBRE_ESTADO
WHERE ID_ESTADO = P_ID_ESTADO;
COMMIT;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL ESTADO CON ID ' || P_ID_ESTADO);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR ESTADO: ' || SQLERRM);
END FIDE_ESTADOS_ACTUALIZAR_SP;

PROCEDURE FIDE_ROLES_ACTUALIZAR_SP(P_ID_ROL NUMBER, P_ROL VARCHAR2, P_ID_ESTADO NUMBER) IS
BEGIN
UPDATE FIDE_ROLES_TB
SET ROL = P_ROL,
ID_ESTADO = P_ID_ESTADO
WHERE ID_ROL = P_ID_ROL;
COMMIT;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL ROL CON ID ' || P_ID_ROL);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR ROL: ' || SQLERRM);
END FIDE_ROLES_ACTUALIZAR_SP;

PROCEDURE FIDE_TIPOS_PAGO_ACTUALIZAR_SP(P_ID_TIPO_PAGO NUMBER, P_TIPO VARCHAR2, P_ID_ESTADO NUMBER) IS
BEGIN
UPDATE FIDE_TIPOS_PAGO_TB
SET TIPO = P_TIPO,
ID_ESTADO = P_ID_ESTADO
WHERE ID_TIPO_PAGO = P_ID_TIPO_PAGO;
COMMIT;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL TIPO DE PAGO CON ID ' || P_ID_TIPO_PAGO);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR TIPO DE PAGO: ' || SQLERRM);
END FIDE_TIPOS_PAGO_ACTUALIZAR_SP;

PROCEDURE FIDE_FORMAS_PAGOS_ACTUALIZAR_SP(P_ID_FORMA_PAGO NUMBER, P_FORMA VARCHAR2, P_ID_ESTADO NUMBER) IS
BEGIN
UPDATE FIDE_FORMAS_PAGOS_TB
SET FORMA = P_FORMA,
ID_ESTADO = P_ID_ESTADO
WHERE ID_FORMA_PAGO = P_ID_FORMA_PAGO;
COMMIT;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO LA FORMA DE PAGO CON ID ' || P_ID_FORMA_PAGO);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR FORMA DE PAGO: ' || SQLERRM);
END FIDE_FORMAS_PAGOS_ACTUALIZAR_SP;

PROCEDURE FIDE_HORARIOS_TURNOS_ACTUALIZAR_SP(P_ID_HORARIO NUMBER, P_HORARIO_TURNO VARCHAR2, P_ID_ESTADO NUMBER) IS
BEGIN
UPDATE FIDE_HORARIOS_TURNOS_TB
SET HORARIO_TURNO = P_HORARIO_TURNO,
ID_ESTADO = P_ID_ESTADO
WHERE ID_HORARIO = P_ID_HORARIO;
COMMIT;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL HORARIO CON ID ' || P_ID_HORARIO);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR HORARIO DE TURNO: ' || SQLERRM);
END FIDE_HORARIOS_TURNOS_ACTUALIZAR_SP;

PROCEDURE FIDE_FECHAS_TURNOS_ACTUALIZAR_SP(P_ID_FECHAS NUMBER, P_FECHAS_TURNO DATE, P_ID_ESTADO NUMBER) IS
BEGIN
UPDATE FIDE_FECHAS_TURNOS_TB
SET FECHAS_TURNO = P_FECHAS_TURNO,
ID_ESTADO = P_ID_ESTADO
WHERE ID_FECHAS = P_ID_FECHAS;
COMMIT;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO LA FECHA DE TURNO CON ID ' || P_ID_FECHAS);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR FECHA DE TURNO: ' || SQLERRM);
END FIDE_FECHAS_TURNOS_ACTUALIZAR_SP;

PROCEDURE FIDE_TIPOS_ESPACIOS_ACTUALIZAR_SP(P_ID_TIPO_ESPACIO NUMBER, P_NOMBRE_ESPACIO VARCHAR2, P_DESCR_ESPACIO VARCHAR2, P_ID_ESTADO NUMBER) IS
BEGIN
UPDATE FIDE_TIPOS_ESPACIOS_TB
SET NOMBRE_ESPACIO = P_NOMBRE_ESPACIO,
DESCR_ESPACIO = P_DESCR_ESPACIO,
ID_ESTADO = P_ID_ESTADO
WHERE ID_TIPO_ESPACIO = P_ID_TIPO_ESPACIO;
COMMIT;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL TIPO DE ESPACIO CON ID ' || P_ID_TIPO_ESPACIO);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR TIPO DE ESPACIO: ' || SQLERRM);
END FIDE_TIPOS_ESPACIOS_ACTUALIZAR_SP;

PROCEDURE FIDE_TIPOS_EVENTOS_ACTUALIZAR_SP(P_ID_TIPO_EVENTO NUMBER, P_TIPO_EVENTO VARCHAR2, P_ID_ESTADO NUMBER) IS
BEGIN
UPDATE FIDE_TIPOS_EVENTOS_TB
SET TIPO_EVENTO = P_TIPO_EVENTO,
ID_ESTADO = P_ID_ESTADO
WHERE ID_TIPO_EVENTO = P_ID_TIPO_EVENTO;
COMMIT;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL TIPO DE EVENTO CON ID ' || P_ID_TIPO_EVENTO);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR TIPO DE EVENTO: ' || SQLERRM);
END FIDE_TIPOS_EVENTOS_ACTUALIZAR_SP;

PROCEDURE FIDE_TIPOS_SERVICIOS_ACTUALIZAR_SP(P_ID_TIPO_SERVICIO NUMBER, P_TIPO_SERVICIO VARCHAR2, P_ID_ESTADO NUMBER) IS
BEGIN
UPDATE FIDE_TIPOS_SERVICIOS_TB
SET TIPO_SERVICIO = P_TIPO_SERVICIO,
ID_ESTADO = P_ID_ESTADO
WHERE ID_TIPO_SERVICIO = P_ID_TIPO_SERVICIO;
COMMIT;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL TIPO DE SERVICIO CON ID ' || P_ID_TIPO_SERVICIO);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR TIPO DE SERVICIO: ' || SQLERRM);
END FIDE_TIPOS_SERVICIOS_ACTUALIZAR_SP;

PROCEDURE FIDE_PERSONAS_ACTUALIZAR_SP(P_ID_PERSONA NUMBER, P_NOMBRE VARCHAR2, P_APELLIDO_PATERNO VARCHAR2, P_APELLIDO_MATERNO VARCHAR2, P_FECHA_REGISTRO DATE, P_ID_ROL NUMBER, P_ID_ESTADO NUMBER) IS
BEGIN
UPDATE FIDE_PERSONAS_TB
SET NOMBRE = P_NOMBRE,
APELLIDO_PATERNO = P_APELLIDO_PATERNO,
APELLIDO_MATERNO = P_APELLIDO_MATERNO,
FECHA_REGISTRO = P_FECHA_REGISTRO,
ID_ROL = P_ID_ROL,
ID_ESTADO = P_ID_ESTADO
WHERE ID_PERSONA = P_ID_PERSONA;
COMMIT;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO LA PERSONA CON CEDULA ' || P_ID_PERSONA);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR PERSONA: ' || SQLERRM);
END FIDE_PERSONAS_ACTUALIZAR_SP;

PROCEDURE FIDE_TELEFONOS_ACTUALIZAR_SP(P_ID_TELEFONO NUMBER, P_ID_PERSONA NUMBER, P_TELEFONO VARCHAR2, P_ID_ESTADO NUMBER) IS
BEGIN
UPDATE FIDE_TELEFONOS_TB
SET ID_PERSONA = P_ID_PERSONA,
TELEFONO = P_TELEFONO,
ID_ESTADO = P_ID_ESTADO
WHERE ID_TELEFONO = P_ID_TELEFONO;
COMMIT;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL TELEFONO CON ID ' || P_ID_TELEFONO);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR TELEFONO: ' || SQLERRM);
END FIDE_TELEFONOS_ACTUALIZAR_SP;

PROCEDURE FIDE_CORREOS_ACTUALIZAR_SP(P_ID_CORREO NUMBER, P_ID_PERSONA NUMBER, P_CORREO VARCHAR2, P_ID_ESTADO NUMBER) IS
BEGIN
UPDATE FIDE_CORREOS_TB
SET ID_PERSONA = P_ID_PERSONA,
CORREO = P_CORREO,
ID_ESTADO = P_ID_ESTADO
WHERE ID_CORREO = P_ID_CORREO;
COMMIT;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL CORREO CON ID ' || P_ID_CORREO);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR CORREO: ' || SQLERRM);
END FIDE_CORREOS_ACTUALIZAR_SP;

PROCEDURE FIDE_RESIDENCIAS_ACTUALIZAR_SP(P_ID_RESIDENCIA NUMBER, P_MONTO_ALQUILER NUMBER, P_MONTO_MANTENIMIENTO NUMBER, P_ID_TIPO_PAGO NUMBER, P_ID_ESTADO NUMBER) IS
BEGIN
UPDATE FIDE_RESIDENCIAS_TB
SET MONTO_ALQUILER = P_MONTO_ALQUILER,
MONTO_MANTENIMIENTO = P_MONTO_MANTENIMIENTO,
ID_TIPO_PAGO = P_ID_TIPO_PAGO,
ID_ESTADO = P_ID_ESTADO
WHERE ID_RESIDENCIA = P_ID_RESIDENCIA;
COMMIT;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO LA RESIDENCIA CON ID ' || P_ID_RESIDENCIA);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR RESIDENCIA: ' || SQLERRM);
END FIDE_RESIDENCIAS_ACTUALIZAR_SP;

PROCEDURE FIDE_RESIDENTES_ACTUALIZAR_SP(P_ID_PERSONA NUMBER, P_ID_RESIDENCIA NUMBER, P_ID_ESTADO NUMBER) IS
BEGIN
UPDATE FIDE_RESIDENTES_TB
SET ID_ESTADO = P_ID_ESTADO
WHERE ID_PERSONA = P_ID_PERSONA
AND ID_RESIDENCIA = P_ID_RESIDENCIA;
COMMIT;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL RESIDENTE ' || P_ID_PERSONA || ' EN LA RESIDENCIA ' || P_ID_RESIDENCIA);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR RESIDENTE: ' || SQLERRM);
END FIDE_RESIDENTES_ACTUALIZAR_SP;

PROCEDURE FIDE_EVENTOS_ACTUALIZAR_SP(P_ID_EVENTO NUMBER, P_DESCR_EVENTO VARCHAR2, P_FECHA_EVENTO DATE, P_ID_TIPO_EVENTO NUMBER, P_ID_TIPO_ESPACIO NUMBER, P_ID_ESTADO NUMBER) IS
BEGIN
UPDATE FIDE_EVENTOS_TB
SET DESCR_EVENTO = P_DESCR_EVENTO,
FECHA_EVENTO = P_FECHA_EVENTO,
ID_TIPO_EVENTO = P_ID_TIPO_EVENTO,
ID_TIPO_ESPACIO = P_ID_TIPO_ESPACIO,
ID_ESTADO = P_ID_ESTADO
WHERE ID_EVENTO = P_ID_EVENTO;
COMMIT;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL EVENTO CON ID ' || P_ID_EVENTO);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR EVENTO: ' || SQLERRM);
END FIDE_EVENTOS_ACTUALIZAR_SP;

PROCEDURE FIDE_VEHICULOS_ACTUALIZAR_SP(P_PLACA VARCHAR2, P_DESCRIPCION VARCHAR2, P_ID_TIPO_ESPACIO NUMBER, P_ID_PERSONA NUMBER, P_ID_ESTADO NUMBER) IS
BEGIN
UPDATE FIDE_VEHICULOS_TB
SET DESCRIPCION = P_DESCRIPCION,
ID_TIPO_ESPACIO = P_ID_TIPO_ESPACIO,
ID_PERSONA = P_ID_PERSONA,
ID_ESTADO = P_ID_ESTADO
WHERE PLACA = P_PLACA;
COMMIT;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL VEHICULO CON PLACA ' || P_PLACA);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR VEHICULO: ' || SQLERRM);
END FIDE_VEHICULOS_ACTUALIZAR_SP;

PROCEDURE FIDE_SERVICIOS_ACTUALIZAR_SP(P_ID_SERVICIO NUMBER, P_DESCR_SERVICIO VARCHAR2, P_FECHA_SALIDA DATE, P_ID_TIPO_SERVICIO NUMBER, P_ID_TIPO_EVENTO NUMBER, P_ID_ESTADO NUMBER) IS
BEGIN
UPDATE FIDE_SERVICIOS_TB
SET DESCR_SERVICIO = P_DESCR_SERVICIO,
FECHA_SALIDA = P_FECHA_SALIDA,
ID_TIPO_SERVICIO = P_ID_TIPO_SERVICIO,
ID_TIPO_EVENTO = P_ID_TIPO_EVENTO,
ID_ESTADO = P_ID_ESTADO
WHERE ID_SERVICIO = P_ID_SERVICIO;
COMMIT;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL SERVICIO CON ID ' || P_ID_SERVICIO);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR SERVICIO: ' || SQLERRM);
END FIDE_SERVICIOS_ACTUALIZAR_SP;

PROCEDURE FIDE_FACTURAS_ACTUALIZAR_SP(P_ID_FACTURA NUMBER, P_FECHA_FACTURA DATE, P_DESCR_FACTURA VARCHAR2, P_ID_TIPO_PAGO NUMBER, P_ID_FORMA_PAGO NUMBER, P_ID_PERSONA NUMBER, P_ID_ESTADO NUMBER) IS
BEGIN
UPDATE FIDE_FACTURAS_TB
SET FECHA_FACTURA = P_FECHA_FACTURA,
DESCR_FACTURA = P_DESCR_FACTURA,
ID_TIPO_PAGO = P_ID_TIPO_PAGO,
ID_FORMA_PAGO = P_ID_FORMA_PAGO,
ID_PERSONA = P_ID_PERSONA,
ID_ESTADO = P_ID_ESTADO
WHERE ID_FACTURA = P_ID_FACTURA;
COMMIT;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO LA FACTURA CON ID ' || P_ID_FACTURA);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR FACTURA: ' || SQLERRM);
END FIDE_FACTURAS_ACTUALIZAR_SP;

PROCEDURE FIDE_CONSULTAS_ACTUALIZAR_SP(P_ID_CONSULTA NUMBER, P_CONSULTA VARCHAR2, P_FECHA_CONSULTA DATE, P_ID_PERSONA NUMBER, P_ID_ESTADO NUMBER) IS
BEGIN
UPDATE FIDE_CONSULTAS_TB
SET CONSULTA = P_CONSULTA,
FECHA_CONSULTA = P_FECHA_CONSULTA,
ID_PERSONA = P_ID_PERSONA,
ID_ESTADO = P_ID_ESTADO
WHERE ID_CONSULTA = P_ID_CONSULTA;
COMMIT;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO LA CONSULTA CON ID ' || P_ID_CONSULTA);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR CONSULTA: ' || SQLERRM);
END FIDE_CONSULTAS_ACTUALIZAR_SP;

PROCEDURE FIDE_REPORTES_ACTUALIZAR_SP(P_ID_REPORTE NUMBER, P_REPORTE VARCHAR2, P_FECHA_REPORTE DATE, P_ID_PERSONA NUMBER, P_ID_ESTADO NUMBER) IS
BEGIN
UPDATE FIDE_REPORTES_TB
SET REPORTE = P_REPORTE,
FECHA_REPORTE = P_FECHA_REPORTE,
ID_PERSONA = P_ID_PERSONA,
ID_ESTADO = P_ID_ESTADO
WHERE ID_REPORTE = P_ID_REPORTE;
COMMIT;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL REPORTE CON ID ' || P_ID_REPORTE);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR REPORTE: ' || SQLERRM);
END FIDE_REPORTES_ACTUALIZAR_SP;

PROCEDURE FIDE_SALARIOS_ACTUALIZAR_SP(P_ID_PERSONA NUMBER, P_MONTO NUMBER, P_TIPO_PAGO NUMBER, P_ID_FORMA_PAGO NUMBER, P_ID_ESTADO NUMBER) IS
BEGIN
UPDATE FIDE_SALARIOS_TB
SET MONTO = P_MONTO,
TIPO_PAGO = P_TIPO_PAGO,
ID_FORMA_PAGO = P_ID_FORMA_PAGO,
ID_ESTADO = P_ID_ESTADO
WHERE ID_PERSONA = P_ID_PERSONA;
COMMIT;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL SALARIO DE LA PERSONA ' || P_ID_PERSONA);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR SALARIO: ' || SQLERRM);
END FIDE_SALARIOS_ACTUALIZAR_SP;

PROCEDURE FIDE_PAQUETES_ACTUALIZAR_SP(P_ID_PAQUETE NUMBER, P_ID_PERSONA NUMBER, P_ID_RESIDENCIA NUMBER, P_FECHA_INGRESO DATE, P_FECHA_SALIDA DATE, P_ID_ESTADO NUMBER) IS
BEGIN
UPDATE FIDE_PAQUETES_TB
SET ID_PERSONA = P_ID_PERSONA,
ID_RESIDENCIA = P_ID_RESIDENCIA,
FECHA_INGRESO = P_FECHA_INGRESO,
FECHA_SALIDA = P_FECHA_SALIDA,
ID_ESTADO = P_ID_ESTADO
WHERE ID_PAQUETE = P_ID_PAQUETE;
COMMIT;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL PAQUETE CON ID ' || P_ID_PAQUETE);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR PAQUETE: ' || SQLERRM);
END FIDE_PAQUETES_ACTUALIZAR_SP;

PROCEDURE FIDE_TURNOS_ACTUALIZAR_SP(P_ID_PERSONA NUMBER, P_ID_FECHAS NUMBER, P_ID_HORARIO NUMBER, P_ID_ESTADO NUMBER) IS
BEGIN
UPDATE FIDE_TURNOS_TB
SET ID_ESTADO = P_ID_ESTADO
WHERE ID_PERSONA = P_ID_PERSONA
AND ID_FECHAS = P_ID_FECHAS
AND ID_HORARIO = P_ID_HORARIO;
COMMIT;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL TURNO DE LA PERSONA ' || P_ID_PERSONA);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR TURNO: ' || SQLERRM);
END FIDE_TURNOS_ACTUALIZAR_SP;

PROCEDURE FIDE_VISITAS_ACTUALIZAR_SP(P_ID_VISITA NUMBER, P_ID_PERSONA NUMBER, P_FECHA_INGRESO DATE, P_FECHA_SALIDA DATE, P_ID_RESIDENCIA NUMBER, P_ID_ROL NUMBER, P_ID_ESTADO NUMBER) IS
BEGIN
UPDATE FIDE_VISITAS_TB
SET ID_PERSONA = P_ID_PERSONA,
FECHA_INGRESO = P_FECHA_INGRESO,
FECHA_SALIDA = P_FECHA_SALIDA,
ID_RESIDENCIA = P_ID_RESIDENCIA,
ID_ROL = P_ID_ROL,
ID_ESTADO = P_ID_ESTADO
WHERE ID_VISITA = P_ID_VISITA;
COMMIT;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO LA VISITA CON ID ' || P_ID_VISITA);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR VISITA: ' || SQLERRM);
END FIDE_VISITAS_ACTUALIZAR_SP;

PROCEDURE FIDE_PERSONAS_SERVICIOS_ACTUALIZAR_SP(P_ID_SERVICIO NUMBER, P_ID_PERSONA NUMBER, P_ID_ESTADO NUMBER) IS
BEGIN
UPDATE FIDE_PERSONAS_SERVICIOS_TB
SET ID_ESTADO = P_ID_ESTADO
WHERE ID_SERVICIO = P_ID_SERVICIO
AND ID_PERSONA = P_ID_PERSONA;
COMMIT;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO LA ASIGNACION DE LA PERSONA ' || P_ID_PERSONA || ' AL SERVICIO ' || P_ID_SERVICIO);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR ASIGNACION DE SERVICIO: ' || SQLERRM);
END FIDE_PERSONAS_SERVICIOS_ACTUALIZAR_SP;

PROCEDURE FIDE_RESUMENES_TURNOS_ACTUALIZAR_SP(P_ID_RESUMEN NUMBER, P_DESCRIPCION VARCHAR2, P_ID_FECHAS NUMBER, P_ID_HORARIO NUMBER, P_ID_CONSULTA NUMBER, P_ID_REPORTE NUMBER, P_ID_ESTADO NUMBER) IS
BEGIN
UPDATE FIDE_RESUMENES_TURNOS_TB
SET DESCRIPCION = P_DESCRIPCION,
ID_FECHAS = P_ID_FECHAS,
ID_HORARIO = P_ID_HORARIO,
ID_CONSULTA = P_ID_CONSULTA,
ID_REPORTE = P_ID_REPORTE,
ID_ESTADO = P_ID_ESTADO
WHERE ID_RESUMEN = P_ID_RESUMEN;
COMMIT;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL RESUMEN DE TURNO CON ID ' || P_ID_RESUMEN);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR RESUMEN DE TURNO: ' || SQLERRM);
END FIDE_RESUMENES_TURNOS_ACTUALIZAR_SP;