FUNCTION FIDE_TOTAL_FACTURAS_PERSONA_FN(P_ID_PERSONA NUMBER) RETURN NUMBER IS
V_TOTAL NUMBER := 0;
BEGIN
FOR REG IN (
SELECT COUNT(*) AS TOTAL
FROM FIDE_FACTURAS_TB
WHERE ID_PERSONA = P_ID_PERSONA
) LOOP
V_TOTAL := REG.TOTAL;
END LOOP;
RETURN V_TOTAL;
END FIDE_TOTAL_FACTURAS_PERSONA_FN;
 
FUNCTION FIDE_MONTO_FACTURADO_PERSONA_FN(P_ID_PERSONA NUMBER) RETURN NUMBER IS
V_TOTAL NUMBER := 0;
BEGIN
FOR REG IN (
SELECT COUNT(F.ID_FACTURA) AS TOTAL
FROM FIDE_FACTURAS_TB F
WHERE F.ID_PERSONA = P_ID_PERSONA
AND F.ID_ESTADO = 1
) LOOP
V_TOTAL := REG.TOTAL;
END LOOP;
RETURN V_TOTAL;
END FIDE_MONTO_FACTURADO_PERSONA_FN;
 
FUNCTION FIDE_TOTAL_VISITAS_RESIDENCIA_FN(P_ID_RESIDENCIA NUMBER) RETURN NUMBER IS
V_TOTAL NUMBER := 0;
BEGIN
FOR REG IN (
SELECT COUNT(*) AS TOTAL
FROM FIDE_VISITAS_TB
WHERE ID_RESIDENCIA = P_ID_RESIDENCIA
) LOOP
V_TOTAL := REG.TOTAL;
END LOOP;
RETURN V_TOTAL;
END FIDE_TOTAL_VISITAS_RESIDENCIA_FN;
 
FUNCTION FIDE_TOTAL_PAQUETES_RESIDENCIA_FN(P_ID_RESIDENCIA NUMBER) RETURN NUMBER IS
V_TOTAL NUMBER := 0;
BEGIN
FOR REG IN (
SELECT COUNT(*) AS TOTAL
FROM FIDE_PAQUETES_TB
WHERE ID_RESIDENCIA = P_ID_RESIDENCIA
) LOOP
V_TOTAL := REG.TOTAL;
END LOOP;
RETURN V_TOTAL;
END FIDE_TOTAL_PAQUETES_RESIDENCIA_FN;
 
FUNCTION FIDE_TOTAL_VEHICULOS_PERSONA_FN(P_ID_PERSONA NUMBER) RETURN NUMBER IS
V_TOTAL NUMBER := 0;
BEGIN
FOR REG IN (
SELECT COUNT(*) AS TOTAL
FROM FIDE_VEHICULOS_TB
WHERE ID_PERSONA = P_ID_PERSONA
) LOOP
V_TOTAL := REG.TOTAL;
END LOOP;
RETURN V_TOTAL;
END FIDE_TOTAL_VEHICULOS_PERSONA_FN;
 
FUNCTION FIDE_TOTAL_SERVICIOS_PERSONA_FN(P_ID_PERSONA NUMBER) RETURN NUMBER IS
V_TOTAL NUMBER := 0;
BEGIN
FOR REG IN (
SELECT COUNT(*) AS TOTAL
FROM FIDE_PERSONAS_SERVICIOS_TB
WHERE ID_PERSONA = P_ID_PERSONA
) LOOP
V_TOTAL := REG.TOTAL;
END LOOP;
RETURN V_TOTAL;
END FIDE_TOTAL_SERVICIOS_PERSONA_FN;
 
FUNCTION FIDE_TOTAL_TURNOS_GUARDIA_FN(P_ID_PERSONA NUMBER) RETURN NUMBER IS
CURSOR_TURNOS SYS_REFCURSOR;
V_TOTAL NUMBER := 0;
BEGIN
OPEN CURSOR_TURNOS FOR
SELECT COUNT(*)
FROM FIDE_TURNOS_TB
WHERE ID_PERSONA = P_ID_PERSONA;
FETCH CURSOR_TURNOS INTO V_TOTAL;
CLOSE CURSOR_TURNOS;
RETURN V_TOTAL;
END FIDE_TOTAL_TURNOS_GUARDIA_FN;
 
FUNCTION FIDE_TOTAL_EVENTOS_TIPO_FN(P_ID_TIPO_EVENTO NUMBER) RETURN NUMBER IS
CURSOR_EVENTOS SYS_REFCURSOR;
V_TOTAL NUMBER := 0;
BEGIN
OPEN CURSOR_EVENTOS FOR
SELECT COUNT(*)
FROM FIDE_EVENTOS_TB
WHERE ID_TIPO_EVENTO = P_ID_TIPO_EVENTO;
FETCH CURSOR_EVENTOS INTO V_TOTAL;
CLOSE CURSOR_EVENTOS;
RETURN V_TOTAL;
END FIDE_TOTAL_EVENTOS_TIPO_FN;
 
FUNCTION FIDE_TOTAL_RESIDENTES_RESIDENCIA_FN(P_ID_RESIDENCIA NUMBER) RETURN NUMBER IS
CURSOR_RESIDENTES SYS_REFCURSOR;
V_TOTAL NUMBER := 0;
BEGIN
OPEN CURSOR_RESIDENTES FOR
SELECT COUNT(*)
FROM FIDE_RESIDENTES_TB
WHERE ID_RESIDENCIA = P_ID_RESIDENCIA;
FETCH CURSOR_RESIDENTES INTO V_TOTAL;
CLOSE CURSOR_RESIDENTES;
RETURN V_TOTAL;
END FIDE_TOTAL_RESIDENTES_RESIDENCIA_FN;
 
FUNCTION FIDE_TOTAL_CONSULTAS_PERSONA_FN(P_ID_PERSONA NUMBER) RETURN NUMBER IS
CURSOR_CONSULTAS SYS_REFCURSOR;
V_TOTAL NUMBER := 0;
BEGIN
OPEN CURSOR_CONSULTAS FOR
SELECT COUNT(*)
FROM FIDE_CONSULTAS_TB
WHERE ID_PERSONA = P_ID_PERSONA;
FETCH CURSOR_CONSULTAS INTO V_TOTAL;
CLOSE CURSOR_CONSULTAS;
RETURN V_TOTAL;
END FIDE_TOTAL_CONSULTAS_PERSONA_FN;
 
FUNCTION FIDE_TOTAL_REPORTES_PERSONA_FN(P_ID_PERSONA NUMBER) RETURN NUMBER IS
CURSOR_REPORTES SYS_REFCURSOR;
V_TOTAL NUMBER := 0;
BEGIN
OPEN CURSOR_REPORTES FOR
SELECT COUNT(*)
FROM FIDE_REPORTES_TB
WHERE ID_PERSONA = P_ID_PERSONA;
FETCH CURSOR_REPORTES INTO V_TOTAL;
CLOSE CURSOR_REPORTES;
RETURN V_TOTAL;
END FIDE_TOTAL_REPORTES_PERSONA_FN;
 
FUNCTION FIDE_TOTAL_FACTURAS_ESTADO_FN(P_ID_ESTADO NUMBER) RETURN NUMBER IS
V_TOTAL NUMBER := 0;
BEGIN
FOR REG IN (
SELECT COUNT(*) AS TOTAL
FROM FIDE_FACTURAS_TB
WHERE ID_ESTADO = P_ID_ESTADO
) LOOP
V_TOTAL := REG.TOTAL;
END LOOP;
RETURN V_TOTAL;
END FIDE_TOTAL_FACTURAS_ESTADO_FN;
 
FUNCTION FIDE_TOTAL_FACTURAS_TIPO_PAGO_FN(P_ID_TIPO_PAGO NUMBER) RETURN NUMBER IS
V_TOTAL NUMBER := 0;
BEGIN
FOR REG IN (
SELECT COUNT(*) AS TOTAL
FROM FIDE_FACTURAS_TB
WHERE ID_TIPO_PAGO = P_ID_TIPO_PAGO
) LOOP
V_TOTAL := REG.TOTAL;
END LOOP;
RETURN V_TOTAL;
END FIDE_TOTAL_FACTURAS_TIPO_PAGO_FN;
 
FUNCTION FIDE_TOTAL_FACTURAS_FORMA_PAGO_FN(P_ID_FORMA_PAGO NUMBER) RETURN NUMBER IS
V_TOTAL NUMBER := 0;
BEGIN
FOR REG IN (
SELECT COUNT(*) AS TOTAL
FROM FIDE_FACTURAS_TB
WHERE ID_FORMA_PAGO = P_ID_FORMA_PAGO
) LOOP
V_TOTAL := REG.TOTAL;
END LOOP;
RETURN V_TOTAL;
END FIDE_TOTAL_FACTURAS_FORMA_PAGO_FN;
 
FUNCTION FIDE_TOTAL_SERVICIOS_TIPO_FN(P_ID_TIPO_SERVICIO NUMBER) RETURN NUMBER IS
V_TOTAL NUMBER := 0;
BEGIN
FOR REG IN (
SELECT COUNT(*) AS TOTAL
FROM FIDE_SERVICIOS_TB
WHERE ID_TIPO_SERVICIO = P_ID_TIPO_SERVICIO
) LOOP
V_TOTAL := REG.TOTAL;
END LOOP;
RETURN V_TOTAL;
END FIDE_TOTAL_SERVICIOS_TIPO_FN;