PROCEDURE FIDE_ESTADOS_ELIMINAR_SP(P_ID_ESTADO NUMBER) IS
BEGIN
DELETE FROM FIDE_ESTADOS_TB
WHERE ID_ESTADO = P_ID_ESTADO;
COMMIT;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL ESTADO CON ID ' || P_ID_ESTADO);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR ESTADO: ' || SQLERRM);
END FIDE_ESTADOS_ELIMINAR_SP;

PROCEDURE FIDE_ROLES_ELIMINAR_SP(P_ID_ROL NUMBER) IS
BEGIN
UPDATE FIDE_ROLES_TB
SET ID_ESTADO = 2
WHERE ID_ROL = P_ID_ROL;
COMMIT;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL ROL CON ID ' || P_ID_ROL);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR ROL: ' || SQLERRM);
END FIDE_ROLES_ELIMINAR_SP;

PROCEDURE FIDE_TIPOS_PAGO_ELIMINAR_SP(P_ID_TIPO_PAGO NUMBER) IS
BEGIN
UPDATE FIDE_TIPOS_PAGO_TB
SET ID_ESTADO = 2
WHERE ID_TIPO_PAGO = P_ID_TIPO_PAGO;
COMMIT;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL TIPO DE PAGO CON ID ' || P_ID_TIPO_PAGO);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR TIPO DE PAGO: ' || SQLERRM);
END FIDE_TIPOS_PAGO_ELIMINAR_SP;

PROCEDURE FIDE_FORMAS_PAGOS_ELIMINAR_SP(P_ID_FORMA_PAGO NUMBER) IS
BEGIN
UPDATE FIDE_FORMAS_PAGOS_TB
SET ID_ESTADO = 2
WHERE ID_FORMA_PAGO = P_ID_FORMA_PAGO;
COMMIT;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO LA FORMA DE PAGO CON ID ' || P_ID_FORMA_PAGO);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR FORMA DE PAGO: ' || SQLERRM);
END FIDE_FORMAS_PAGOS_ELIMINAR_SP;

PROCEDURE FIDE_HORARIOS_TURNOS_ELIMINAR_SP(P_ID_HORARIO NUMBER) IS
BEGIN
UPDATE FIDE_HORARIOS_TURNOS_TB
SET ID_ESTADO = 2
WHERE ID_HORARIO = P_ID_HORARIO;
COMMIT;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL HORARIO CON ID ' || P_ID_HORARIO);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR HORARIO DE TURNO: ' || SQLERRM);
END FIDE_HORARIOS_TURNOS_ELIMINAR_SP;

PROCEDURE FIDE_FECHAS_TURNOS_ELIMINAR_SP(P_ID_FECHAS NUMBER) IS
BEGIN
UPDATE FIDE_FECHAS_TURNOS_TB
SET ID_ESTADO = 2
WHERE ID_FECHAS = P_ID_FECHAS;
COMMIT;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO LA FECHA DE TURNO CON ID ' || P_ID_FECHAS);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR FECHA DE TURNO: ' || SQLERRM);
END FIDE_FECHAS_TURNOS_ELIMINAR_SP;

PROCEDURE FIDE_TIPOS_ESPACIOS_ELIMINAR_SP(P_ID_TIPO_ESPACIO NUMBER) IS
BEGIN
UPDATE FIDE_TIPOS_ESPACIOS_TB
SET ID_ESTADO = 2
WHERE ID_TIPO_ESPACIO = P_ID_TIPO_ESPACIO;
COMMIT;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL TIPO DE ESPACIO CON ID ' || P_ID_TIPO_ESPACIO);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR TIPO DE ESPACIO: ' || SQLERRM);
END FIDE_TIPOS_ESPACIOS_ELIMINAR_SP;

PROCEDURE FIDE_TIPOS_EVENTOS_ELIMINAR_SP(P_ID_TIPO_EVENTO NUMBER) IS
BEGIN
UPDATE FIDE_TIPOS_EVENTOS_TB
SET ID_ESTADO = 2
WHERE ID_TIPO_EVENTO = P_ID_TIPO_EVENTO;
COMMIT;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL TIPO DE EVENTO CON ID ' || P_ID_TIPO_EVENTO);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR TIPO DE EVENTO: ' || SQLERRM);
END FIDE_TIPOS_EVENTOS_ELIMINAR_SP;

PROCEDURE FIDE_TIPOS_SERVICIOS_ELIMINAR_SP(P_ID_TIPO_SERVICIO NUMBER) IS
BEGIN
UPDATE FIDE_TIPOS_SERVICIOS_TB
SET ID_ESTADO = 2
WHERE ID_TIPO_SERVICIO = P_ID_TIPO_SERVICIO;
COMMIT;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL TIPO DE SERVICIO CON ID ' || P_ID_TIPO_SERVICIO);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR TIPO DE SERVICIO: ' || SQLERRM);
END FIDE_TIPOS_SERVICIOS_ELIMINAR_SP;

PROCEDURE FIDE_PERSONAS_ELIMINAR_SP(P_ID_PERSONA NUMBER) IS
BEGIN
UPDATE FIDE_PERSONAS_TB
SET ID_ESTADO = 2
WHERE ID_PERSONA = P_ID_PERSONA;
COMMIT;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO LA PERSONA CON CEDULA ' || P_ID_PERSONA);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR PERSONA: ' || SQLERRM);
END FIDE_PERSONAS_ELIMINAR_SP;

PROCEDURE FIDE_TELEFONOS_ELIMINAR_SP(P_ID_TELEFONO NUMBER) IS
BEGIN
UPDATE FIDE_TELEFONOS_TB
SET ID_ESTADO = 2
WHERE ID_TELEFONO = P_ID_TELEFONO;
COMMIT;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL TELEFONO CON ID ' || P_ID_TELEFONO);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR TELEFONO: ' || SQLERRM);
END FIDE_TELEFONOS_ELIMINAR_SP;

PROCEDURE FIDE_CORREOS_ELIMINAR_SP(P_ID_CORREO NUMBER) IS
BEGIN
UPDATE FIDE_CORREOS_TB
SET ID_ESTADO = 2
WHERE ID_CORREO = P_ID_CORREO;
COMMIT;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL CORREO CON ID ' || P_ID_CORREO);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR CORREO: ' || SQLERRM);
END FIDE_CORREOS_ELIMINAR_SP;

PROCEDURE FIDE_RESIDENCIAS_ELIMINAR_SP(P_ID_RESIDENCIA NUMBER) IS
BEGIN
UPDATE FIDE_RESIDENCIAS_TB
SET ID_ESTADO = 2
WHERE ID_RESIDENCIA = P_ID_RESIDENCIA;
COMMIT;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO LA RESIDENCIA CON ID ' || P_ID_RESIDENCIA);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR RESIDENCIA: ' || SQLERRM);
END FIDE_RESIDENCIAS_ELIMINAR_SP;

PROCEDURE FIDE_RESIDENTES_ELIMINAR_SP(P_ID_PERSONA NUMBER, P_ID_RESIDENCIA NUMBER) IS
BEGIN
UPDATE FIDE_RESIDENTES_TB
SET ID_ESTADO = 2
WHERE ID_PERSONA = P_ID_PERSONA
AND ID_RESIDENCIA = P_ID_RESIDENCIA;
COMMIT;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL RESIDENTE ' || P_ID_PERSONA || ' EN LA RESIDENCIA ' || P_ID_RESIDENCIA);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR RESIDENTE: ' || SQLERRM);
END FIDE_RESIDENTES_ELIMINAR_SP;

PROCEDURE FIDE_EVENTOS_ELIMINAR_SP(P_ID_EVENTO NUMBER) IS
BEGIN
UPDATE FIDE_EVENTOS_TB
SET ID_ESTADO = 2
WHERE ID_EVENTO = P_ID_EVENTO;
COMMIT;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL EVENTO CON ID ' || P_ID_EVENTO);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR EVENTO: ' || SQLERRM);
END FIDE_EVENTOS_ELIMINAR_SP;

PROCEDURE FIDE_VEHICULOS_ELIMINAR_SP(P_PLACA VARCHAR2) IS
BEGIN
UPDATE FIDE_VEHICULOS_TB
SET ID_ESTADO = 2
WHERE PLACA = P_PLACA;
COMMIT;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL VEHICULO CON PLACA ' || P_PLACA);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR VEHICULO: ' || SQLERRM);
END FIDE_VEHICULOS_ELIMINAR_SP;

PROCEDURE FIDE_SERVICIOS_ELIMINAR_SP(P_ID_SERVICIO NUMBER) IS
BEGIN
UPDATE FIDE_SERVICIOS_TB
SET ID_ESTADO = 2
WHERE ID_SERVICIO = P_ID_SERVICIO;
COMMIT;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL SERVICIO CON ID ' || P_ID_SERVICIO);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR SERVICIO: ' || SQLERRM);
END FIDE_SERVICIOS_ELIMINAR_SP;

PROCEDURE FIDE_FACTURAS_ELIMINAR_SP(P_ID_FACTURA NUMBER) IS
BEGIN
UPDATE FIDE_FACTURAS_TB
SET ID_ESTADO = 2
WHERE ID_FACTURA = P_ID_FACTURA;
COMMIT;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO LA FACTURA CON ID ' || P_ID_FACTURA);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR FACTURA: ' || SQLERRM);
END FIDE_FACTURAS_ELIMINAR_SP;

PROCEDURE FIDE_CONSULTAS_ELIMINAR_SP(P_ID_CONSULTA NUMBER) IS
BEGIN
UPDATE FIDE_CONSULTAS_TB
SET ID_ESTADO = 2
WHERE ID_CONSULTA = P_ID_CONSULTA;
COMMIT;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO LA CONSULTA CON ID ' || P_ID_CONSULTA);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR CONSULTA: ' || SQLERRM);
END FIDE_CONSULTAS_ELIMINAR_SP;

PROCEDURE FIDE_REPORTES_ELIMINAR_SP(P_ID_REPORTE NUMBER) IS
BEGIN
UPDATE FIDE_REPORTES_TB
SET ID_ESTADO = 2
WHERE ID_REPORTE = P_ID_REPORTE;
COMMIT;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL REPORTE CON ID ' || P_ID_REPORTE);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR REPORTE: ' || SQLERRM);
END FIDE_REPORTES_ELIMINAR_SP;

PROCEDURE FIDE_SALARIOS_ELIMINAR_SP(P_ID_PERSONA NUMBER) IS
BEGIN
UPDATE FIDE_SALARIOS_TB
SET ID_ESTADO = 2
WHERE ID_PERSONA = P_ID_PERSONA;
COMMIT;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL SALARIO DE LA PERSONA ' || P_ID_PERSONA);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR SALARIO: ' || SQLERRM);
END FIDE_SALARIOS_ELIMINAR_SP;

PROCEDURE FIDE_PAQUETES_ELIMINAR_SP(P_ID_PAQUETE NUMBER) IS
BEGIN
UPDATE FIDE_PAQUETES_TB
SET ID_ESTADO = 2
WHERE ID_PAQUETE = P_ID_PAQUETE;
COMMIT;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL PAQUETE CON ID ' || P_ID_PAQUETE);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR PAQUETE: ' || SQLERRM);
END FIDE_PAQUETES_ELIMINAR_SP;

PROCEDURE FIDE_TURNOS_ELIMINAR_SP(P_ID_PERSONA NUMBER, P_ID_FECHAS NUMBER, P_ID_HORARIO NUMBER) IS
BEGIN
UPDATE FIDE_TURNOS_TB
SET ID_ESTADO = 2
WHERE ID_PERSONA = P_ID_PERSONA
AND ID_FECHAS = P_ID_FECHAS
AND ID_HORARIO = P_ID_HORARIO;
COMMIT;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL TURNO DE LA PERSONA ' || P_ID_PERSONA);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR TURNO: ' || SQLERRM);
END FIDE_TURNOS_ELIMINAR_SP;

PROCEDURE FIDE_VISITAS_ELIMINAR_SP(P_ID_VISITA NUMBER) IS
BEGIN
UPDATE FIDE_VISITAS_TB
SET ID_ESTADO = 2
WHERE ID_VISITA = P_ID_VISITA;
COMMIT;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO LA VISITA CON ID ' || P_ID_VISITA);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR VISITA: ' || SQLERRM);
END FIDE_VISITAS_ELIMINAR_SP;

PROCEDURE FIDE_PERSONAS_SERVICIOS_ELIMINAR_SP(P_ID_SERVICIO NUMBER, P_ID_PERSONA NUMBER) IS
BEGIN
UPDATE FIDE_PERSONAS_SERVICIOS_TB
SET ID_ESTADO = 2
WHERE ID_SERVICIO = P_ID_SERVICIO
AND ID_PERSONA = P_ID_PERSONA;
COMMIT;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO LA ASIGNACION DE LA PERSONA ' || P_ID_PERSONA || ' AL SERVICIO ' || P_ID_SERVICIO);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR ASIGNACION DE SERVICIO: ' || SQLERRM);
END FIDE_PERSONAS_SERVICIOS_ELIMINAR_SP;

PROCEDURE FIDE_RESUMENES_TURNOS_ELIMINAR_SP(P_ID_RESUMEN NUMBER) IS
BEGIN
UPDATE FIDE_RESUMENES_TURNOS_TB
SET ID_ESTADO = 2
WHERE ID_RESUMEN = P_ID_RESUMEN;
COMMIT;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL RESUMEN DE TURNO CON ID ' || P_ID_RESUMEN);
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR RESUMEN DE TURNO: ' || SQLERRM);
END FIDE_RESUMENES_TURNOS_ELIMINAR_SP;